
@echo off
setlocal enabledelayedexpansion

set currDir=%~dp0

echo -----------------------------------
echo Assembling assets... Please wait...
echo -----------------------------------


cd "!currDir!"

echo Assembling autogenerated definitions...

call "AssembleDefs.bat" noPause


cd "!currDir!"

call "AssembleGraphics.bat" noPause


cd "!currDir!"

echo Assembling tables...

call "AssembleTables.bat" noPause


cd "!currDir!"

echo Assembling text...

call "AssembleText.bat" noPause


cd "!currDir!"

echo Assembling music...

call "AssembleMusic.bat" noPause noRefs


cd "!currDir!"
echo Assembling maps...

call "AssembleMaps.bat" noPause


cd "!currDir!"

call "MAKEAnims.bat" noPause


cd "!currDir!"

call "MAKEHACK.bat" noPause noSaveCopy

pause
