
@echo off
setlocal enabledelayedexpansion

rem This will try to assemble everything that has a script to auto-assemble it.
rem For now, Pyhton and Java are required on the machine to build everything, but I plan to change that eventually.

set currDir=%~dp0

echo --------------------------------------------------------
echo Assembling everything and building ROM... Please wait...
echo --------------------------------------------------------

cd "!currDir!"

echo Assembling autogenerated definitions...

call "AssembleDefs.bat" noPause


cd "!currDir!"

call "AssembleGraphics.bat" noPause


cd "!currDir!"
rem Reeee I can't make tmx2ea not pause!
echo Assembling maps...

call "AssembleMaps.bat" noPause


cd "!currDir!"

echo Assembling music...

call "AssembleMusic.bat" noPause noRefs


cd "!currDir!"

echo Assembling tables...

call "AssembleTables.bat" noPause


cd "!currDir!"

echo Assembling text...

call "AssembleText.bat" noPause


cd "!currDir!"

call "MAKEAnims.bat" noPause


cd "!currDir!"

call "MAKEHACK.bat" noPause noSaveCopy

pause
