
## Merc7BanditDisbandBeginningText
[FarRight][LoadPlayer][Right][LoadAdlez][MidLeft][LoadEfil]
I have come to my decision.[A]
[FarRight]Yes?[A]
[Right]Really? You'll help us?[A]
[MidLeft]In a way. We'll help each other.[A]
[Right]You have a deal.[A][CloseSpeech][MidLeft][MoveFarLeft][Right][MoveLeft][Right][LoadKendrick]
You really aren't a businessman,[NL]
you know that, Adlez? You don't[A][NL]
even know what he's asking.[A]
[FarRight]Surprisingly, Kendrick is right. We want[NL]
to hear what Efil has to say first.[A]
[FarLeft]Thank you, [Tact]. Sit back, and listen[NL]
closely. You came to me wanting to end the[A][NL]
war between Cesaria and Arcanae, correct?[A]
[FarRight]Yes, that's a good way to put it.[A]
[FarLeft]I suppose I can't blame you[NL]
for your ignorance.[A]
[Left]Ignorance?[A]
[FarRight]Please, Efil. Explain it to us.[NL]
We want to understand why you[A][NL]
feel the way that you do.[A]
[FarLeft]Why explain it to you when[NL]
I can show it to you?[A]
[FarRight]Show it?[A]
[FarLeft]I have the power to let you view my[NL]
memories. It will require much[A][NL]
concentration, but can be done. I suppose[NL]
you'll want some context first, however.[A][NL]
Cesaria and Arcanae were at war. That much[NL]
was the same. But the chaos it was[A][NL]
creating had aroused the Guradian[NL]
Spirit, Kilthel, and his Four Orden.[A]
[Left]Four Orden?[A]
[FarLeft]Four immortal beings that served Kilthel[NL]
as the commanders of his armies of[A][NL]
Guardian Spirits, as well as his bodyguards[NL]
and agents. They were extremely powerful[A][NL]
warriors. They'd had 1,000 years to hone[NL]
their craft, after all. I joined an[A][NL]
ancient group of warriors, the Sateenkaari,[NL]
and quickly rose to their leader in[A][NL]
order to combat these Four Orden.[A]
[FarRight]So then what happened?[A]
[FarLeft]That's where it becomes easier[NL]
to show you than to tell you.[A][X]

## Merc7BanditDisbandStartFlashbackText
[MidLeft][LoadUzkalis][MidRight][LoadEfil]
Uzkalis! How goes it?[A]
[MidLeft]Efil! Back already?[NL]
Did you find anything?[A]
[MidRight]Nothing good... The overflow of Vene[NL]
is starting to spread from Arcanae's[A][NL]
capital. If we don't move quickly, the Four[NL]
Orden will strike before we can. Or worse,[A][NL]
the Vene will start corrupting the land...[A]
[MidLeft]We need to explain the situation to Arcanae[NL]
The Vene they're pouring into their[A][NL]
research will just bite us all in the ass.[A]
[MidRight]Arcanae won't stop unless we can[NL]
get Cesaria to agree to a truce...[A]
[MidLeft]Why not talk to Lieutenant Maximus?[NL]
With the death of Captain Darren, I'm[A][NL]
sure Maximus has some influence now...[A]
[MidRight]It's definitely worth a shot. But Servius,[NL]
Arveldir, and Xylia are on the move. Kilthel[A][NL]
may be inactive, but his Orden are not.[A]
[MidLeft]We're spread too thin, Efil. We need[NL]
more support for the Sateenkaari.[A][NL]
You can't just keep hiding this[NL]
issue from the rest of Avenir.[A]
[MidRight]What would you have me do? Let Avenir[NL]
fall into panic? We can't afford that.[A]
[MidLeft]Then let's meet with Maximus. I'm sure he[NL]
can talk to General Leyos. I have[A][NL]
connections in Arcanae. Xavus is still[NL]
there, he can help organize a[A][NL]
talk between the two countries.[A]
[MidRight]If we can get the two countries to[NL]
call a truce long enough to deal[A][NL]
with Kilthel and the Four Orden...[A]
[MidLeft]Just three of them.[A]
[MidRight]Yeah. I know. Let's get going[NL]
to Cesaria. We can't waste any time.[A]
[MidLeft]Agreed.[A][X]

## Merc7BanditDisbandMaximusHereFlashbackText
[Right][LoadEfil][MidLeft][LoadMaximus]
Ah, Efil. It's been awhile.[A]
[Right]Indeed it has. How has your[NL]
new station been treating you?[A]
[MidLeft]Very well.[A][FarRight][LoadUzkalis]
Maximus.[A]
[MidLeft][LoadMaximus]Uzkalis!? Efil, why did[NL]
you bring him here?[A]
[Right]Calm down. He's seen past the[NL]
war between your nations. He's[A][NL]
with the Sateenkaari now.[A]
[MidLeft]You and your Sateenkaari...[NL]
What is really the problem here?[A]
[Right]Arcanae just wants freedom[NL]
to pursue their research.[A]
[MidLeft]Research that they'll use[NL]
to dominate Avenir.[A]
[Right]That's irrelevant. As they research,[NL]
Vene and Inge become more and more[A][NL]
unbalanced in favor of Vene. You've been to[NL]
Draterus. You know what it's like.[A][NL]
All of Avenir will be like that[NL]
if we can't do something.[A]
[MidLeft]But what do you intend to[NL]
do? Stop Arcanae?[A]
[FarRight]Arcanae won't stop their research because[NL]
it "might" destroy Avenir. But if their[A][NL]
lives are threatened, they'll stop.[A]
[MidLeft]Threatening them isn't[NL]
any different from war.[A]
[Right]We aren't the ones threatening. Guardian[NL]
Spirit Kilthel and the Four Orden are[A][NL]
planning on eradicating all human life in[NL]
Avenir. The release of all that Inge[A][NL]
would not only prevent the destruction[NL]
of Arcanae, but also potentially[A][NL]
resurrect Vathryl.[A]
[MidLeft][TMM]...[.....][TMM] Oh. I see. I'm only familiar with[NL]
one of the Four Orden. Servius was the[A][NL]
one who killed Darren, my predecessor. But[NL]
it seems far-fetched that the Guardian[A][NL]
Spirit, the one supposedly meant to[NL]
defend Avenir from annihilation,[A][NL]
would take such drastic measures?[A]
[Right]In his eyes, humanity is destroying[NL]
Avenir. He has to save Avenir[A][NL]
from it's inhabitants, I suppose.[A]
[MidLeft]He's really going that far?[NL]
It seems extremely far-fetched[A]
[Right]I remember...[A]
[FarRight]You have influence. If you can work with[NL]
us to convince Arcanae of this eventuality,[A][NL]
then we have a chance to stand up to Kilthel.[NL]
Cesaria, Arcanae, the Sateenkaari, even[A][NL]
Haedric and Altia. Kilthel may be a Guardian[NL]
Spirit with some all-powerful immortal[A][NL]
henchmen, but we would be victorious.[A]
[MidLeft][TMM]...[......][TMM] I'll talk to General Leyos.[NL]
We may be able to arrange a cease-fire,[A][NL]
but you'll need to talk to Arcanae.[A]
[Right]We already have Xavus on the job.[A]
[MidLeft]That's good, that's good... I'll get talking[NL]
to General Leyos then. You both should[A][NL]
return to your temple. If what you say[NL]
is true, I fear our time runs short.[A]
[Right]You're correct. Thank you, Maximus.[A]
[MidLeft][Smile]Thank me when Kilthel lays with[NL]
a sword through his heart.[A]
[Right][Smile]Heh. Will do.[A][X]

## Merc7BanditDisbandXyliaAttackingFlashbackText
[Right][LoadEfil][FarRight][LoadUzkalis][FarLeft][LoadSoldier2]
[FarLeft]Efil! Xylia of the Four[NL]
Orden is attacking![A]
[Right][LoadEfil]What!? How?[A]
[FarLeft]She warped herself and a horde of Vathrylian[NL]
Guardians here! We're totally outmatched![A][ClearFace]
[FarRight]Efil, we're out of time. We have to[NL]
move towards the Temple of Kilthel, now.[A][CloseSpeech][Right][MoveMidLeft]
But, the Sateenkaari...[A][CloseSpeech][FarRight][MoveMidRight]
They can hold Xylia here. Kilthel is[A][NL]
without half his Orden right now. If we can[NL]
defeat them, Xylia won't matter anymore.[A]
[MidLeft][LoadEfil]You're willing to[NL]
make that sacrifice!?[A]
[MidRight]You don't have to leave everyone[NL]
for dead. Sound a general retreat.[A][NL]
We can abandon this temple.[A]
[MidLeft]How do you propose we keep Xylia here?[A]
[MidRight]I can work with some of the other mages[NL]
to cast a seal. She'll be trapped here.[A]
[MidLeft][TMM]...[.....][TMM] Do it. The rest of us will[NL]
make towards the Temple of Kilthel[A][NL]
in Draterus. It's time to end this.[A]
[MidRight]I'll meet you there. I intend to be[NL]
there when we end Kilthel's reign.[A][X]

## Merc7BanditDisbandAtTempleFlashbackText
[MidRight][LoadEfil]
This is it. We're here.[A][FarLeft][LoadMaximus]
Efil![A]
[MidRight]Maximus! You're here![A][X]

## Merc7BanditDisbandUzkalisTempleFlashbackText
[FarRight][LoadEfil][Right][LoadMaximus][MidLeft][LoadUzkalis]
I made it. The seal is set. Xylia is trapped[NL]
inside the temple. Most of the Sateenkaari[A][NL]
made it out safely. There were too many[NL]
Vathrylian guardians, though. It would've[A][NL]
been impossible to guarantee all of them.[A]
[FarRight]I understand, Uzkalis. Thank you.[A]
[Right]So this is it? The final battle?[A]
[FarRight]Yes. We take the blade to Kilthel.[NL]
This is humanity's final stand.[A]
[MidLeft]I'm clamoring in anticipation.[A]
[FarRight]Uzkalis, have the rest of our companions[NL]
deal with the Vathrylian guardians[A][NL]
around. We're heading straight for[NL]
Kilthel and the last two Orden.[A]
[Right]Servius, a swordsman on par with any Basileus,[NL]
and Arveldir, the former King of the Elves.[A]
[MidLeft]Having second thoughts, Maximus?[A]
[Right]Only in your dreams, Uzkalis. Let's go.[A][X]

## Merc7BanditDisbandInTempleFlashbackText
[Left][LoadKilthel][FarRight][LoadMaximus][Right][LoadEfil]
Kilthel![A]
[Left]Oh, we have visitors... Right[NL]
at the moment of truth...[A]
[FarRight]Your reign has come to[NL]
an end, Lord Kilthel.[A][FarLeft][LoadArveldir]
I wouldn't be so confident in your words,[NL]
newly dubbed Captain Maximus. You may[A][NL]
find an arrow between your eyes.[A][FarRight][ClearFace][LoadUzkalis]
What is faster, I wonder?[NL]
Your arrow, or my lightning?[A]
[Left]Calm yourself, Arveldir. These mortals[NL]
are nothing to us. Soon, they will be[A][NL]
gone, no more than dust in the wind.[A]
[FarRight]That's just what you think. Xylia is[NL]
sealed away. She can't do anything[A][NL]
more to help you. It's just[NL]
you three. We aren't alone.[A]
[Left]Ah, your precious friends, yes? They will[NL]
fade along with you. Our spell is almost[A][NL]
complete... When I cast it, all mortals in[NL]
Avenir will disperse into Inge and Vene.[A][NL]
This will bring the energies into balance.[A]
[FarRight]You're upset over what happened to[NL]
Vathryl. So you think treating the rest[A][NL]
of humanity to an equally destructive[NL]
fate is anything better? Is that it?[A]
[Left]I wouldn't expect you to understand...[A]
[FarLeft]May I kill him now?[A]
[FarRight]Give it your best shot...[A][X]

## Merc7BanditDisbandArveldirDeadFlashbackText
[Left][LoadKilthel][Right][LoadEfil][FarRight][LoadUzkalis][FarLeft][LoadArveldir]
My... lord...[A][ClearFace]
[FarRight]You may be immortal, but that[NL]
doesn't give you superhuman strength.[A]
[Left]Hmph. Seems I've miscalculated. Servius![A][FarLeft][LoadServius]
Yes?[A]
[Left]Leave the rest of this spell[NL]
to me. Deal with them.[A]
[Right]You're going to stand by him, Servius?[A]
[FarLeft]I am not a traitor to my old friend.[A]
[Right]But-[A]
[FarLeft]I've said my part, Efil. Accept your fate[NL]
or kill me. Those are your two options.[A][FarRight][ClearFace][LoadMaximus]
Efil, we don't have time.[NL]
I'll deal with Servius.[A]
[FarLeft]Ha! You? Your captain could not even[NL]
withstand one strike from my blade.[A]
[FarRight]It is true. But Darren was an[NL]
ignorant, overconfident fool. I will[A][NL]
not make the same mistakes he did.[A]
[FarLeft]Very well then. Let me test[NL]
what you say, then.[A]
[FarRight]Draw your sword![A][X]

## Merc7BanditDisbandEfilPanicsFlashbackText
[Right][LoadEfil]Maximus![A][X]

## Merc7BanditDisbandServiusDeadFlashbackText
[FarLeft][LoadServius][Left][LoadKilthel][Right][LoadEfil][FarRight][LoadMaximus]
Darren may have been corrupt, but he[NL]
didn't deserve to die so[A][NL]
pathetically. This was for him.[A]
[FarLeft]Perhaps...[.....] Human[CloseEyes]ity isn't[NL]
doomed...[....] With men like you...[A][ClearFace]
[Left]Servius! How have you all-[A]
[Right]We aren't going to just let[NL]
you exterminate all of us.[A]
[Left]I am the Guardian Spirit! I[NL]
do this to protect Avenir![A]
[Right]Protecting Avenir does not just[NL]
include protecting the land. You[A][NL]
have to protect the people, too.[A]
[Left]You are a fool, Efil... Let me show[NL]
you the power of the Higher Beings![A][X]

## Merc7BanditDisbandKilthelDeathText
[FarRight][LoadEfil]
Consider your[NL]
power revoked.[A][X]

## Merc7BanditDisbandKilthelDeadText
[FarRight][LoadUzkalis][Right][LoadEfil][MidLeft][LoadKilthel]
Efil...[....] You...[....] How...[A]
[Right]You're outdated, Kilthel.[NL]
Humanity wants a new guardian.[A]
[MidLeft]This will never rest... [CloseEyes]The war between[NL]
Cesaria and Arcanae...[....] You've only[A][NL]
temporarily ceased it... Even now...[....][NL]
Xylia lays the roots...[A]
[Right]What? Xylia is sealed away![A]
[MidLeft][OpenEyes]Heh heh heh... Goodbye, Avenir...[A][ClearFace]
[Right]Kilthel! No! Dammit![A]
[FarRight]What did he mean by Xylia[NL]
is laying the roots?[A][MidLeft][LoadMaximus]
I don't know. But with her and her army of[NL]
Vathrylian Guardians cooped up in the[A][NL]
temple, I doubt we'll want to[NL]
remove that seal anytime soon.[A]
[Events]
[FarRight]Efil, I transferred control over[NL]
that seal to you. Whatever you feel[A][NL]
is best to do, I leave up to you.[A]
[Right]Ah, sorry?[A]
[FarRight]You okay, Efil?[A]
[Right]Just wondering what Kilthel meant...[A]
[MidLeft]He's dead now. Let's head back[NL]
to our countries. Perhaps things[A][NL]
may be able to return to normal.[A]
[FarRight]I'll be returning to Arcanae.[NL]
Thank you for allowing me to[A][NL]
accompany you on this journey, Efil.[A]
[Right]Thank you, both. I would never have[NL]
been able to do it without you two.[A][NL]
Or anyone else. All of the Sateenkaari.[NL]
You all helped me. Thank you.[A][X]

## Merc7BanditDisbandLeaveFlashbackText
[MidLeft][LoadEfil][FarRight][LoadAdlez][Right][LoadPlayer]
It was so different then...[NL]
What happened with him?[A]
[MidLeft]The Thunder Magi at the time was executed,[NL]
and Uzkalis rose to the title, but the three[A][NL]
eldest Magi did not respect his voice. That[NL]
is why Uzkalis and Xavus have lead the[A][NL]
armies of Arcanae against Cesaria.[A]
[FarRight]Against... Cesaria? So the war now[NL]
is entirely different from the war then?[A]
[MidLeft]Yes. You are correct. You see, even though[NL]
Xylia remains sealed in the temple, she[A][NL]
was a master of Vene. She can use it to[NL]
influence emotions, and most of all, dreams.[A][NL]
She's spent the past ten years doing this to[NL]
the leaders of both Cesaria and Arcanae,[A][NL]
building the hate between the two countries.[A]
[Right]You're telling me that their[NL]
war is artificial? It's[A][NL]
not as bad as it should be?[A]
[MidLeft]Yes. So long as Xylia lives, there's no[NL]
hope of peace. Uzkalis and Xavus are too[A][NL]
passionate about their vision for Arcanae,[NL]
the other Magi are too passionately[A][NL]
against it and have aligned with Cesaria,[NL]
where General Rex is strongly opposed[A][NL]
to Arcanae. Ideally, they could have[NL]
reached a peaceful agreement after[A][NL]
Kilthel's death, but Xylia's[NL]
manipulations are too powerful.[A]
[FarRight]So let me guess. You intend for us to go to[NL]
the Temple and kill her, once and for all?[A]
[MidLeft]That about sums it up, yes.[A]
[Right]I'm guessing you couldn't do this[NL]
yourself because her army of Vathrylian[A][NL]
Guardians is still there too?[A]
[MidLeft]Yeah. The Sateenkaari are disbanded. I[NL]
couldn't ask this of them. But I[A][NL]
hate to see my old friends at[NL]
each other's throats like this...[A][NL]
[Right]I understand. If you think this[NL]
is the most important step in[A][NL]
stopping the war... I will help you.[A]
[FarRight]I'm with [Tact]. You've showed us what[NL]
we need to know. I'd love to make her[A][NL]
head roll. She sounds like a right bitch.[A]
[MidLeft]Do you think your friends will join me?[A]
[Right]I'll have to talk to[NL]
them. It's their choice.[A]
[MidLeft][Smile]I appreciate it.[A][X]

## Merc7BanditDisbandVicarText
[FarLeft][LoadWalter][Left][LoadBaret][MidRight][LoadVicar]
So that's what it is, eh?[NL]
What do you think, boys?[A]
[FarLeft]I'm going to help Efil. I don't care[NL]
if you and Baret don't. We've travelled[A][NL]
this far with [Tact], I'll stand with him.[A]
[Left]You know me. I'm enthusiastic about any[NL]
fight. Against a 1,000 year old magic[A][NL]
prodigy with an army? Sign me up.[A]
[MidRight]If both of you are in, I'm in. [Tact],[NL]
I trust you know the risks of this?[A][CloseSpeech][MidRight][MoveRight][FarRight][LoadPlayer]
Yes, but I want to stand with Efil.[A]
[Right]That's good enough for me. Go talk[NL]
to Kendrick and Arya. I think[A][NL]
they're around here somewhere.[A][X]

## Merc7BanditDisbandAryaKendrickText
[FarLeft][LoadArya][MidRight][LoadPlayer][Left][LoadKendrick]
I was the one who talked Efil into[NL]
trusting all of you in the first[A][NL]
place. Of course I'm in, [Tact].[A]
[MidRight]Thanks, Kendrick. Arya?[A]
[FarLeft]I will journey with you as well. I've come[NL]
this far. Even though we Shizonians are[A][NL]
hired assassins, we advocate peace within[NL]
Avenir. If this gets us a step closer[A][NL]
to that, then it is worth it.[A]
[MidRight]Thank you, Arya. You've been a remarkably[NL]
valuable ally these past weeks.[A]
[FarLeft]I'm just doing what is right. You and Adlez[NL]
may have been bandits, but you have[A][NL]
good intentions, ironic as it may be.[A][X]

## Merc7BanditDisbandBackWithEfilText
[Right][LoadPlayer][FarRight][LoadArya][MidLeft][LoadEfil]
I can't thank you all enough for joining[NL]
me in this. I can't guarantee our[A][NL]
survival, or even that killing[NL]
Xylia will solve our problem.[A]
[Right]You showed us the past. I believe[NL]
you are correct. If not,[A][NL]
we'll have at least done a[NL]
good service to Avenir.[A]
[FarRight][Tact] is right. It's not even a matter of[NL]
the war. Seals don't last forever. Killing[A][NL]
Xylia is a more permanent solution.[A][ClearFace][LoadAdlez]
So, Efil, how do we get to this Temple[NL]
of the Sateenkaari where she's sealed?[A]
[MidLeft]It's to the far north of Draterus, nestled[NL]
amongst the low mountains. Very few[A][NL]
people travel to that part of Avenir,[NL]
so it was the perfect location.[A][FarRight][ClearFace][LoadArya]
Surprisingly strategic...[A]
[MidLeft]We were trying to hide from an all-knowing[NL]
spirit, we kind of had to think it through.[A]
[Right]Let's get going. We have a[NL]
1,000-year-old Orden to kill.[A][X]

## Merc7BanditDisbandOutsideTempleText
[FarLeft][LoadBaret][Right][LoadPlayer][FarRight][LoadAdlez][Left][LoadEfil]
This is it... I know you're[NL]
in there, Xylia...[A]
[Right]It's not too late to[NL]
turn back, Efil...[A]
[Left]No, I must do this...[A]
[FarRight]Be on your guard, everyone.[A]
[FarLeft]I always am.[A]
[Left]Breaking the seal is as easy as[NL]
just entering the temple.[A]
[FarLeft]Let's go, then.[A][X]

## Merc7BanditDisbandMeetXyliaText
[Right][LoadEfil][FarRight][LoadAdlez][MidLeft][LoadXylia]
I was wondering when you'd come, Efil.[A]
[Right]It's been awhile, Xylia. Ten years, yet[NL]
you've remained a thorn in Avenir's side.[A]
[MidLeft]I'm the thorn? I'M the thorn? That's[NL]
rich, coming from the one who[A][NL]
murdered the Guardian Spirit.[A]
[Right]You're blind.[A]
[MidLeft]I wouldn't expect you to understand.[NL]
Kilthel was my friend. You killed him.[A][NL]
I'm only letting his legacy live on.[A]
[FarRight]By manipulating the emotions and dreams[NL]
of leaders in both Arcanae and Cesaria[A][NL]
so that they fight? Do you realize[NL]
how many have died because of you?[A]
[MidLeft]Do you realize how many would die if Arcanae[NL]
is permitted to continue their research?[A][NL]
All of you will dry up and turn to dust[NL]
with the imbalance of Inge and[A][NL]
Vene. Trust me when I say that Kilthel's[NL]
method would be far less painless.[A][FarRight][ClearFace][LoadPlayer]
Stop.[A]
[MidLeft]Excuse me?[A]
[FarRight]I'm a Haedrician. So are most of the rest[NL]
of us. You think we want to die[A][NL]
because of some form of "mercy" that[NL]
Kilthel promised? Hell no. We only[A][NL]
go down fighting. I would rather[NL]
fight against an unstoppable[A][NL]
blight and wear myself down to[NL]
death than fade away because[A][NL]
some "god" commanded it. And we[NL]
certainly aren't gonna go down[A][NL]
because two countries are fighting[NL]
that shouldn't be fighting![A]
[MidLeft]You talk a good game, dog. I[NL]
think you'll be the first I kill.[A]
[Right]Not me?[A]
[MidLeft]No, Efil, you will be the last. I[NL]
will make it slow and painful for you.[A][FarRight][ClearFace][LoadKendrick]
You know? I suddenly don't care that[NL]
she's influencing the war. I really[A][NL]
want to put my axe to her neck.[A][Right][ClearFace][LoadAdlez]
I'm with you on that, Kendrick.[A]
[FarRight]I'll race you to it.[A]
[MidLeft]Enough! We've talked enough. Let us see, Efil,[NL]
if you remember my old friends, the[A][NL]
Vathrylian Guardians. If you can't[NL]
get through them, you have no[A][NL]
hope of getting through me![A][Right][ClearFace][LoadEfil]
My friends, the time is now! We can't[NL]
let her live! The Guardians are[A][NL]
irrelevant, only Xylia matters![A][X]

## Merc7BanditDisbandEfilReachesSpotText
[MidLeft][LoadEfil]
This area... It feels as though something[NL]
lingers here... [Tact]! Hold[FarRight][LoadPlayer][MidLeft] off the[A][NL]
guardians for a moment! I[NL]
want to try something...[A]
[FarRight]You've got it, Efil.[A][X]

## Merc7BanditDisbandChapterFlashbackText
[MidRight][LoadXylia][MidLeft][LoadKilthel]
Xylia, is everything okay?[A]
[MidRight]Ye-yes of course. I've just been[NL]
slightly worried about Servius recently...[A]
[MidLeft]Why's that?[A]
[MidRight]Well, the Grand Sorcerer has been exploring[NL]
his experiments more and more recently, and[A][NL]
the royal family has given their full approval,[NL]
so long as Servius watches over them.[A]
[MidLeft]I don't understand why that worries[NL]
you so. Servius is more than just[A][NL]
an amazingly capable swordsman, you know.[A]
[MidRight]I know, but if something goes[NL]
wrong, what could happen to him?[A]
[MidLeft]If something goes wrong, I doubt[NL]
he'd be the only one affected.[A]
[MidRight]Do you feel it, Kilthel?[A]
[MidLeft]Feel what?[A][CloseSpeech][MidRight][MoveRight][FarRight][LoadArveldir]
I do, Xylia.[A]
[MidLeft]What's going on?[A]
[FarRight]The experiments are affecting the levels of[NL]
Vene. Haven't you noticed that this summer[A][NL]
has been one of the warmest in years?[A]
[MidLeft]I suppose I had.[A]
[Right]Vene and Inge are meant to be balanced,[NL]
Kilthel. Being right by the source[A][NL]
of this imbalance could warp someone...[A]
[FarRight]Servius has that sword we found up north.[NL]
It absorbs excess Vene, so he'll be fine.[A]
[MidLeft]Besides, the Emperor knows the[NL]
risks with the experiments. That's[A][NL]
why he wanted Servius to observe.[A]
[Right]I just can't help but worry...[A]
[FarRight]You're more attuned to Vene than any of[NL]
us, Xylia. If you feel anything truly[A][NL]
overwhelming, don't hesitate to let us[NL]
know. We're pioneers of a new age,[A][NL]
but none of us know what the[NL]
result of this research could be.[A]
[MidLeft]Arveldir is right. Don't fret too much,[NL]
Xylia, but if you feel a change in the Vene[A][NL]
that's truly concerning, let us know. I[NL]
highly doubt the Grand Sorcerer will[A][NL]
report anything dangerous like that[NL]
to the Royal Family, so we should.[A]
[Right]Right. Of course. Thanks,[NL]
you two. I appreciate it.[A]
[MidLeft][Smile]We're friends, [FarRight][Smile][MidLeft]aren't we?[NL]
We look after each other.[A]
[Right][Smile]Right![A][X]

## Merc7BanditDisbandEndChapterFlashbackText
[MidLeft][LoadEfil]
She didn't lie... They[NL]
truly were friends...[A]
[FarFarRight]Are you about done over there, Efil?[NL]
We're still kind of fighting for our lives![A]
[MidLeft]I'm good! I think I understand Xylia[NL]
a bit better now... but we still[A][NL]
must do what we came here to do.[A][X]

## Merc7BanditDisbandXyliaBattleText
[FarLeft][LoadXylia]
I have studied the arts of[NL]
Vene and light magic for[A][NL]
for over ten times as long[NL]
as you've lived, and yet[A][NL]
you intend to face me?[NL]
Ignorance...[A][X]

## Merc7BanditDisbandEfilXyliaBattleText
[FarLeft][LoadXylia]
Efil... Heh heh heh... I[NL]
guess you made it this[A][NL]
far. Don't expect to make it[NL]
any further. Just because[A][NL]
you defeated my friends does[NL]
not mean you are able[A][NL]
to kill me so easily.[A][ClearFace]
[FarRight][LoadEfil]
You've spent too long in this[NL]
world, Xylia. You cling[A][NL]
too much to the past. It's[NL]
time to move on. If you[A][NL]
can't recognize that, then[NL]
I have no other choice.[A][ClearFace]
[FarLeft][LoadXylia]
You always had a choice,[NL]
Efil. You defied the[A][NL]
Guardian Spirit. Which of us,[NL]
then, is more guilty?[A][ClearFace]
[FarRight][LoadEfil]
I won't go back and forth[NL]
with you. There's no[A][NL]
reason. Let us fight![A][X]

## Merc7BanditDisbandXyliaDeathText
[FarLeft][LoadXylia]
Kilthel...[....] Servius...[....][NL]
Arveldir...[....][CloseEyes] Forgive me...[....][A][NL]
My friends...[A][X]

## Merc7BanditDisbandGoodEndingText
[FarLeft][LoadPlayer][Left][LoadEfil][FarRight][LoadXylia]
Damn you, Efil...[A]
[Left]Xylia... I understand you better now.[A]
[FarRight]How do you mean?[A]
[Left]I saw your memory. Talking with[NL]
Kilthel and Arveldir. You really[A][NL]
were just a group of friends...[A]
[FarRight]Friends who saw the fall of the[NL]
greatest empire in the history of[A][NL]
Avenir, all because of one man's greed![A]
[Left]It drove you insane, Xylia, but times have[NL]
changed. I also had my friends. Maximus[A][NL]
and Uzkalis were just among the few back[NL]
then... And now I have [Tact], and all[A][NL]
of these friends. Your time was[NL]
then, Xylia. Not now.[A]
[FarRight]Ha...[A]
[FarLeft]You have the right to do this,[NL]
Efil. She was your enemy.[A]
[Left]That was ten years ago. My time[NL]
is over. Now, [Tact], it is your time.[A]
[FarLeft]Efil...[A]
[FarRight]Just do it, fool.[A][CloseSpeech][FarLeft][MoveMidRight][....][FarRight][ClearFace][....][Left]
May you rest in peace...[A][FarLeft][LoadArya]
She'd spent 1,000 years trying to fight[NL]
for what she believed was right...[A][NL]
Fighting alongside her friends...[A][MidRight][ClearFace][Right][LoadPlayer][FarRight][LoadAdlez][Left]
1,000 years is too long for any one person[NL]
to exist in this world. It doesn't matter[A][NL]
if they're a Higher Being or not.[A]
[FarRight]I can respect her motivations in the[NL]
context of 1,000 years ago. But here, now?[A]
[Left]Let us hope our actions here[NL]
today have helped Avenir...[A]
[Events]
[FarLeft][ClearFace][LoadKendrick]
I'm planning on heading back to Bacrun to[NL]
see if anything starts to change...[A]
[Left]I will reach out to my old friends[NL]
and see if they are willing[A][NL]
to arrange for peace talks.[A]
[FarRight]I will go with you, Efil.[NL]
This has been a dream of mine,[A][NL]
and I wish to see it through.[A]
[Left]I understand, Adlez.[A][FarRight][ClearFace][LoadArya]
I intend to return to Shizon. Xexim will be most[NL]
interested to hear of what's transpired.[A]
[Left]I'm sure he will. Thank you, Arya,[NL]
and give Xexim my regards.[A]
[FarRight]I will. Good luck, Efil.[A][ClearFace][LoadVicar]
I think we'll be returning to Haedric to[NL]
resume our mercenary work. I hear there's[A][NL]
a bandit clan led by some bastard named[Smile][NL]
Connor that they may need help with.[A][FarLeft][ClearFace][LoadBaret][Smile]
Slitting his throat certainly sounds[NL]
like a good next step for us.[A][Left][ClearFace][LoadWalter][Smile]
It's been a pleasure, [Tact]! When you're[NL]
in Haedric, be sure to give us a call.[A]
[FarLeft]Either for work or for a[NL]
drink. Either is good with me.[A]
[FarRight]I agree with the boys. Keep[NL]
your head on straight, Adlez.[A][FarLeft][ClearFace][LoadAdlez]
I will. You too, Vicar.[A][Left][ClearFace][LoadEfil]
What will you do, [Tact]?[A]
[Right]I'll stay here, for now. The flashbacks[NL]
have intrigued me. I'm wondering if[A][NL]
there's history to be uncovered[NL]
that we don't know or understand.[A]
[Left]A worthy cause. I wish you luck, my[NL]
friend. I'll return to let you[A][NL]
know how the peace talks go.[A]
[Right]Thank you.[A][X]

## Merc7BanditDisbandBadEndingText
[FarLeft][LoadAdlez][Right][LoadPlayer][Left][LoadEfil]
Go to hell, Xylia.[A]
[Right]Efil...[A]
[Left]...[.....] It's done. She's dead.[NL]
The war should be resolved.[A]
[FarLeft]It's not over yet, Efil. We still have[NL]
to make arrangements for peace talks.[A]
[Left]Yes, of course. You're right. I'll get ready to[NL]
move to Cesaria and Arcanae... Uzkalis and[A][NL]
Maximus should be open to speaking to me.[A]
[FarLeft]I'll go with you, Efil. I've dreamed of[NL]
this for years, I intend to see it through.[A][FarRight][LoadArya]
I'm gonna return to Shizon and speak with[NL]
Xexim. He'll want to know what happened.[A]
[Left]Give him my regards, Arya. And thank you[NL]
for everything you've done to help.[A]
[FarRight]It's been my pleasure.[A][ClearFace][LoadKendrick]
I'll be returning to Bacrun. If you[NL]
need my help for anything, Efil,[A][NL]
don't hesitate to send me word.[A]
[Left]I will, Kendrick.[A][Right][ClearFace][LoadWalter][FarRight][ClearFace][LoadBaret][Left][ClearFace][LoadVicar]
I think the boys and I will[NL]
be returning to Haedric.[A]
[FarRight]There's some bandit leader named[NL]
Connor plaguing the land there.[A]
[Right]Don't worry, we'll take care of him.[A]
[FarLeft]Ha! Good luck, you three.[A]
[Left]Thanks, Adlez. You ever need[NL]
mercenaries, don't hesitate to call.[A]
[Right]Same goes for you, [Tact].[A]
[FarRight]If you ever need a sparring partner,[NL]
or even just a drinking buddy,[A][NL]
don't hesitate to call on us.[A][Right][ClearFace][LoadPlayer]
Thank you, all. Good luck[NL]
with your endeavors.[A]
[FarLeft]What will you be doing, [Tact]?[A]
[Right]I want to search through more of[NL]
these ruins. If I can uncover[A][NL]
just a glimpse into Vathryl's history,[NL]
perhaps we can prevent future wars.[A][Left][ClearFace][LoadEfil]
A worthy cause. Good luck,[NL]
[Tact]. May we meet again.[A]
[Right]I'm sure we will. Thank[NL]
you again, Efil.[A][X]

## Merc7BanditDisbandHistoryText
[Left][LoadPlayer]
This is... A history depicting the Guardian[NL]
Spirits... This is huge! This could explain[A][NL]
everything that's happened to Vathryl...[A][X]

## Merc7BanditDisbandNarratorHereText
[MidRight][LoadPlayer][MidLeft][LoadNarrator]
I really must applaud you, [Tact]. You[NL]
were so close to figuring everything[A][NL]
out. It took you long enough.[A]
[MidRight]What? Who are you?[NL]
What do you mean?[A]
[MidLeft]You don't remember who I[NL]
am, even now? Pity...[A]
[MidRight]You're him, aren't you? The Guardian[NL]
Spirit. But why do you seem so familiar?[A]
[MidLeft]Honestly, [Tact], do you remember[NL]
anything? Typical lost soul...[A]
[MidRight]Lost soul... It's all coming back![A]
[MidLeft]Good, good. But you don't know[NL]
what happens next, do you?[A]
[MidRight]What?[A]
[MidLeft]I kill you.[A]
[MidRight]Wha- Why!?[A]
[MidLeft]You've provided a healthy level of[NL]
entertainment for me. Finally killing[A][NL]
Xylia... Took you all long enough, but[NL]
unfortunately, I'm not allowed to let[A][NL]
lost souls influence the events of Avenir[NL]
that much, so, alas, I must kill you. A[A][NL]
simple rolling back of time will solve[NL]
all the rest of our issues.[A]
[MidRight]Don't expect for me to go[NL]
down without a fight![A]
[MidLeft]Yes, yes, I know...[A][X]

## Merc7BanditDisbandEndingPlayerDeathText
[FarRight][LoadPlayer]
Damn... No... Efil...[A][ClearFace]
[FarLeft][LoadNarrator]
A shame. A real shame.[NL]
Maybe I'll give you[A][NL]
another chance, lost soul...[A][X]
