
## Merc4BanditBeginningText
[FarRight][LoadVicar][Right][LoadPlayer][Left][LoadConnor][FarLeft][LoadAdlez]
So, some of them escaped...[A]
[Left]It's clear what we have[NL]
to do. Go after them.[A]
[Right]I thought the goal was just to loot[NL]
the caravan. Who cares if[A][NL]
some of them got away?[A]
[FarRight]Yercheck is a Warlord village. The[NL]
warriors there are far above our[A][NL]
level. Adlez, you know this.[A]
[FarLeft]Vicar has a fair point.[A]
[Left]But our goal! We need[NL]
what was in that caravan![A]
[Right]What was in that caravan?[A]
[FarRight]What goal?[A]
[Left]Dammit...[A]
[FarLeft]This was all your idea, Connor. You[NL]
might as well explain it to them.[A]
[Left]...[.....] Fine. [Tact] knows this much[NL]
already, but we have ambitions of[A][NL]
uniting all of Avenir under one banner.[NL]
But we obviously lack the manpower[A][NL]
and strength to do so. We're just a[NL]
bandit clan after all. That caravan[A][NL]
was carrying an ancient artifact of[NL]
Vathryl, capable of high-level magic[A][NL]
without the user needing to have[NL]
any ability to channel Vene.[A]
[FarRight]You wanted a way for those of us who[NL]
channel Inge to compete with the[A][NL]
magic-casters channeling Vene... It makes[NL]
sense in concept, but your motives...[A]
[Left]Cesaria and Arcanae's war isn't going to[NL]
end without some form of intervention! If[A][NL]
we're gonna take that step, we might as well[NL]
keep going from there! So long as[A][NL]
different countries exist, so[NL][LoadConnor]
will war and violence![A]
[FarLeft]Connor, calm yourself.[A]
[Left]Sorry, boss.[A]
[FarRight]I definitely understand what you're[NL]
trying to accomplish. Adlez, may [Tact][A][NL]
and I speak to you in private?[A]
[FarLeft]Of course. Connor, check[NL]
up on the men.[A]
[Left]I'm on it boss.[A][ClearFace][......][FarLeft][MoveMidLeft]
What is it?[A]
[FarRight]This isn't like you.[A]
[MidLeft]What do you mean?[A][CloseSpeech]
[FarRight][MoveRight]You're an idealist, yes. We both are.[NL]
But the senseless slaughter to get to[A][NL]
your goal... Surely, you know it can't[NL]
succeed? With constant rebellion from[A][NL]
the people you subjugate, peace[NL]
will be only an illusion.[A]
[MidLeft]I am fully aware... Connor's ambitions[NL]
are world domination. He masks it under a[A][NL]
facade of wanting peace, but all he wants[NL]
is power. I'm surprised he hasn't made a[A][NL]
move to kill me yet... Perhaps because[NL]
he knows he lacks the loyalty of[A][NL]
the rest of the clan.[A]
[FarRight]Why do you go along with it then?[A]
[MidLeft]I was once a Haedrician warrior serving[NL]
under Warlord Tyrone. Vicar was as well.[A][NL]
About ten years ago, was it? Basileus Leon[NL]
had suddenly become passive. Haedric was[A][NL]
destined to fall apart. The war between[NL]
Cesaria and Arcanae of that time was[A][NL]
growing, and we felt the world was nearing[NL]
destruction. The hero Efil prevented it,[A][NL]
of course, but now I see it happening again,[NL]
and many people are blind to what they[A][NL]
see. I don't want to cause people pain.[NL]
It brings me pain already knowing the[A][NL]
lives I've taken as a bandit.[A]
[FarRight]But you do it anyway. What's your[NL]
goal, Adlez? What do you want?[A]
[MidLeft]I want to find Efil. If anyone can truly[NL]
resolve the dilemma Avenir finds itself[A][NL]
in, it's him. I figured one of the best[NL]
ways to bring him out of hiding was[A][NL]
bring chaos to Haedric and the other[NL]
nations with Connor's plan. But when[A][NL]
he came, I was going to help him,[NL]
in the best way I could.[A]
[FarRight]So... let me get this straight. Connor[NL]
is using you for power, but in fact,[A][NL]
you're using him to get Efil's attention?[NL]
This has got to be the most politically[A][NL]
strategic bandit clan on the continent.[A]
[Right]Adlez, you were willing to sacrifice[NL]
your morals and perhaps even[A][NL]
your life to bring peace.[A]
[FarRight]You really are an idealist.[A]
[MidLeft]Haha! I'm definitely used to hearing that.[NL]
[Tact], Vicar... I want you to help me.[A][NL]
We're going to go to Yerchek and get that[NL]
artifact. With it, Connor's plan[A][NL]
shouldn't be necessary... It has the power [NL]
to awaken old Vathrylian technology, the[A][NL]
kind that caused that kingdom's destruction[NL]
and the events of ten years ago.[A]
[FarRight]I'm in. I'm just a freelancer, sure,[NL]
but I'd like to think I can help.[A]
[Right]These are ideals I have also supported as[NL]
well. However, I'd like to ask Walter and[A][NL]
Baret their opinion. I'll do that later. If[NL]
they want to leave, that's their choice.[A][NL]
I'm sticking around to see how[NL]
this plays out regardless.[A]
[MidLeft]Thank you, both.[A][X]

## Merc4BanditAryaListensText
[Left][LoadArya]So that's the game that's afoot...[......] I[NL]
need to see how this continues to develop.[A][X]

## Merc4BanditPoliticsText
[FarLeft][LoadWalter][MidRight][LoadVicar][Left][LoadBaret]
So that's their game...[A]
[FarLeft]I never realized just how much political[NL]
plotting happened in a bandit clan...[A]
[MidRight]That's just how it is.[NL]
What will you two do?[A]
[Left]I don't really have a purpose I'm following[NL]
right now. I'll go with you, Vicar.[A]
[FarLeft]I'm with Baret. If you think it's good[NL]
to follow along and see what's[A][NL]
happening, that's good enough for me.[A]
[MidRight]Thank you, both. I hope you know that[NL]
you have no reason to remain bound to me.[A][NL]
I saved your lives, yes, but that means[NL]
precious little if you don't have the[A][NL]
freedom to do what you want.[A]
[FarLeft]This is what I want.[A]
[Left]Likewise.[A]
[MidRight]Tomorrow, we head out for Yerchek.[NL]
Warlord Tyrone will likely be[A][NL]
there... It'll be a tough[NL]
fight. Get your rest.[A][X]

## Merc4BanditVicarFindsAryaText
[MidRight][LoadArya][FarLeft][LoadVicar]
Oh! You're the Shizonian. Arya, was it?[A]
[MidRight]That's right.[A][CloseSpeech][FarLeft][MoveMidLeft]
Will you be joining us for[NL]
our raid on Yerchek tomorrow?[A]
[MidRight]That's my plan. I want to get to[NL]
the bottom of whatever Adlez has planned.[A]
[MidLeft]You're an expert information[NL]
gatherer. I'm sure you've already[A][NL]
got it mostly figured out.[A]
[MidRight]Wha-?[A]
[MidLeft]I know you were listening earlier.[NL]
Baret's been keeping an eye on[A][NL]
you. But you're still with us.[A]
[MidRight]...[......] I want to see how this plays out.[NL]
Adlez has the right idea. Even Connor's[A][NL]
concept... If the nations are united, but[NL]
if we kill Connor, it could create peace.[A]
[MidLeft]So that's your reason for sticking[NL]
around... Yes I suppose so... It[A][NL]
depends a lot on how tomorrow goes.[A]
[MidRight]Yes... I trust [Tact]. However[NL]
he opts to proceed is how we'll[A][NL]
do it. I think both plans[NL]
are viable to the end goal.[A]
[MidLeft]I agree. I'm[Smile] glad to have[NL]
you on our side, Arya.[A]
[MidRight]Likewise. Anyway, let's get some[NL]
rest. Tomorrow will be quite the day...[A][X]

## Merc4BanditTyroneMayorText
[MidLeft][LoadVillagerMan2][FarRight][LoadTyrone][Right][LoadMayor]
Thank you for the information. Start[NL]
making your way to the capital. I[A][NL]
have a feeling that those bandits[A][NL]
will be coming here next...[A]
[MidLeft]I understand. Thank you.[A][ClearFace][....][Right][MoveMidLeft]
Tyrone, what do you think of this?[A][CloseSpeech][FarRight][MoveMidRight]
These are ill tidings... I have no[NL]
doubt the bandits are lead by Adlez.[A][MidLeft][ClearFace][LoadMayor]
Adlez? Wasn't he one of your[NL]
warriors ten years ago?[A]
[MidRight]Yes. Unfortunately, he and I had[NL]
different morals and thoughts about the[A][NL]
conflict between Cesaria and Arcanae, hence[NL]
why he left to form his bandit clan...[A]
[MidLeft]He sounds like a rat.[A]
[MidRight]He's a good man. It's disappointing to see[NL]
him fall so low... I will stay here and[A][NL]
defend the artifact with my life.[A]
[MidLeft]We should have sent it to the capital.[A]
[MidRight]I trust my ability to defend more than I trust[NL]
Basileus Leon's restraint in using it.[A]
[MidLeft]I see. As a Haedrician warrior,[NL]
I am yours to command, Warlord.[A]
[MidRight]Defend your people. Should you fall, I[NL]
fear that they will take the artifact[A][NL]
and use it how they see fit...[A]
[MidLeft]I understand. I shall see you[NL]
after this battle, Tyrone.[A]
[MidRight]Indeed. Good luck.[A][X]

## Merc4BanditEndingBeginningText
[MidLeft][LoadVicar][FarRight][LoadAdlez][Right][LoadPlayer]
This is Yerchek?[A]
[FarRight]Yes. I'm sure both their mayor and[NL]
Warlord Tyrone will be in battle today.[A]
[MidLeft]So it'll be tougher than any[NL]
fight we've done so far.[A]
[FarRight]Hence why I intend to join you. Connor[NL]
is back at the hideout organizing other[A][NL]
men for where we go after this.[NL]
He can't interfere today.[A]
[MidLeft]I see... [Tact], this is a tricky battle[NL]
we fight today. We have all agreed to[A][NL]
place our trust in you. The artifact is[NL]
the goal, Tyrone likely defends the home[A][NL]
where they keep it. Senseless killing is[NL]
not necessarily our goal today, but if[A][NL]
you feel that Connor's methods are the[NL]
way we must resolve this dispute,[A][NL]
we will not stand in your way.[A]
[FarRight]I agree. You are levelheaded, [Tact].[A]
[Right]Thank you, both. I will do my best.[A][MidLeft][ClearFace][LoadArya]
Cut the chatter and focus. It looks[NL]
like the Haedricians are coming.[A][ClearFace][FarLeft][LoadSoldier2]
You there! We're on high security![NL]
State your name and business![A]
[Right]My name is [Tact]. We're here[NL]
to raid your wonderful little town.[A]
[FarLeft]Ha! Warlord Tyrone thought you[NL]
might be coming... To arms![A][NL]
We fight 'til our last breath![A][X]

## Merc4BanditAreaMayorText
[FarRight][LoadMayor]Please. I'll defend this with my life,[NL]
but you don't have to kill me![A][X]

## Merc4BanditMayorBattleText
[FarLeft][LoadMayor]You are ruffians, all of you![NL]
I'll fight to my last breath[A][NL]
to protect my people![A][X]

## Merc4BanditMayorDeathText
[FarLeft][LoadMayor]The artifact musn't...[CloseEyes][NL]
Fall into their hands...[A][X]

## Merc4BanditMayorPlayerBattleText
[FarRight][LoadPlayer]You are the mayor?[A][ClearFace]
[FarLeft][LoadMayor]Yes. You are not any[NL]
I have seen before...[A][ClearFace]
[FarRight][LoadPlayer]My name is [Tact]. I[NL]
believe you were given[A][NL]
something that I need...[A][ClearFace]
[FarLeft][LoadMayor]No! You will only misuse it![A][ClearFace]
[FarRight][LoadPlayer]I wish we could have seen[NL]
eye to eye... Draw your blade![A][X]

## Merc4BanditMayorAdlezBattleText
[FarRight][LoadAdlez]I am sorry...[A][ClearFace]
[FarLeft][LoadMayor]You! You are Adlez,[NL]
are you not?[A][ClearFace]
[FarRight][LoadAdlez]Yes. I wanted to believe that[NL]
perhaps, we could cooperate...[A][ClearFace]
[FarLeft][LoadMayor]How could I ever cooperate[NL]
with a traitor like you!?[A][NL]
Tyrone told me about you...[A][ClearFace]
[FarRight][LoadAdlez]Indeed... He is an honest man.[NL]
You can trust what he says.[A][ClearFace]
[FarLeft][LoadMayor]And that is why I must[NL]
kill you, here and now![A][X]

## Merc4BanditTyroneBattleText
[FarLeft][LoadTyrone]Your lust for power will bring[NL]
your downfall. Allow me[A][NL]
to end this before[NL]
you lose yourself![A][X]

## Merc4BanditTyroneDeathText
[FarLeft][LoadTyrone]Basileus Leon...[CloseEyes][NL]
They are strong...[A][X]

## Merc4BanditTyroneAdlezBattleText
[FarRight][LoadAdlez]Tyrone.[A][ClearFace]
[FarLeft][LoadTyrone]Adlez.[A][ClearFace]
[FarRight][LoadAdlez]Never thought this would[NL]
be where we meet again...[A][ClearFace]
[FarLeft][LoadTyrone]I don't have time for waxing[NL]
sentimental. We're enemies.[A][NL]
Plain and simple.[A][ClearFace]
[FarRight][LoadAdlez]I feared that would be[NL]
your outlook on this...[A][NL]
En garde, my old friend.[A][ClearFace]
[FarLeft][LoadTyrone]En garde![A][X]

## Merc4BanditEndingBanditText
[FarLeft][LoadPlayer][Left][LoadAdlez][MidRight][LoadTyrone]
[CloseEyes]Dammit... Now there's nothing[NL]
between you all and Haedric...[A]
[Left]Tyrone... You were a good[NL]
man. You died with honor.[A]
[MidRight]Do not...[....] Let me be...[....] forgotten...[A][ClearFace]
[Left]I won't.[.....] [Tact], what now?[A]
[FarLeft]The Mayor is dead. The artifact is ours for[NL]
the taking. Baret, Walter,[FarRight][LoadWalter][Right][LoadBaret][FarLeft] search[A][NL]
the building for it.[A]
[FarRight]You can count on me![A][ClearFace]
[Right]I'm on it.[A][ClearFace]
[MidRight][LoadVicar]What do you intend to do now?[A]
[FarLeft]Having killed the mayor and Tyrone, I don't[NL]
think we have a whole lot of choice on how[A][NL]
to move forward. If we abandon Connor's[NL]
plan now, we have no forces to[A][NL]
defend from the coming battle.[A]
[Left]I feared this would be the case... If only[NL]
we had been able to reason with them...[A]
[MidRight]How should we proceed[NL]
from here, then?[A][CloseSpeech][MoveRight]
[FarRight][LoadArya]If I may?[A]
[FarLeft]Of course, Arya.[A]
[FarRight]The first step in this is obviously to[NL]
capture Haedric. But... There's no reason[A][NL]
to eradicate them. Basileus Leon is smart.[NL]
If we could somehow... Reach out to him?[A][NL]
It's well-known that he as well wishes to[NL]
end the war, but doesn't like either side[A][NL]
of the conflict all that much. Perhaps[NL]
maybe he would be willing to go along[A][NL]
with our plan, so to speak?[A]
[Left]Connor and I had discussed the[NL]
potential for that before, but do[A][NL]
you really think it's a possibility?[A]
[FarRight]Shizon keeps tabs on all the rulers and[NL]
politics of Avenir. Basileus Leon lacks[A][NL]
confidence in his own rule, but we believe[NL]
that's the only reason he's never taken[A][NL]
steps to do what you all intend to do now.[A]
[Right]The Basileus? Hm...[A]
[Left]It's a concept that's[NL]
definitely out there.[A]
[FarLeft]What kind of man is[NL]
the Basileus, anyway?[A]
[Right]Leon is... unique among people who have[NL]
held the title of Basileus. While[A][NL]
they're historically selected by a[NL]
tournament, Leon actually rose to his[A][NL]
position when the previous Basileus,[A][NL]
a man named Servius, dubbed him his[NL]
successor and disappeared. That[A][NL]
being said, Leon is still a[NL]
fearsome warrior and a strong leader.[A]
[Left]Leon has done a lot. He's repaired relations[NL]
with a lot of the Warlords, so Haedric is[A][NL]
all-in-all more united now than it ever was[NL]
before. I feel like, if we got him our[A][NL]
side, many of the Warlords would follow.[A]
[FarLeft]What reason does he have to want[NL]
to ally with us though? We killed[A][NL]
Tyrone and stole an artifact.[A]
[FarRight]Haedric may be one nation connected by a[NL]
strong sense of nationalism, but that[A][NL]
doesn't make all of the leaders friends.[NL]
It's almost tradition that every Basileus[A][NL]
wants the Warlords who aren't his friends[NL]
dead. It creates less conflict of opinion.[A]
[Left]Tyrone was not popular with Leon. He was[NL]
the longest serving Warlord, appointed by[A][NL]
the previous Basileus. He always believed[NL]
that, if Haedric had endured as separate[A][NL]
fiefdoms for so long, there was no[NL]
reason to try and unite them. He was[NL]
also violently opposed to any[A][NL]
sort of involvement with the war[NL]
between Cesaria and Arcanae.[A]
[Right]Leon advocated for a council, similar to[NL]
Arcanae, but with the Basileus serving[A][NL]
as a chairman of sorts. I don't think Arya's[NL]
idea is far-fetched. Let's head back and[A][NL]
talk with Connor. This will definitely[NL]
require some planning...[A][X]

## Merc4BanditEndingDisbandText
[FarLeft][LoadPlayer][Left][LoadAdlez][FarRight][LoadMayor][Right][LoadTyrone]
This is it... [CloseEyes][.....]The mayor. Where is he?[A]
[FarRight]I'm here, Warlord Tyrone.[A]
[Right]I leave the matter of the artifact...[....][NL]
to you. You can trust...[.....] Adlez...[A]
[Left]Tyrone...[A]
[Right]Adlez... It is all fine[NL]
now. I do not blame you.[A][ClearFace]
[FarRight]Why did you kill him?[A]
[FarLeft]He stood in our way. It[NL]
didn't have to be this way.[A]
[FarRight]What do you want from us?[A][CloseSpeech][FarLeft][MoveLeft]
The artifact. The original plan laid out by[NL]
Adlez' right hand man had us conquering[A][NL]
Haedric, but it was foolishness...[NL]
I think we can work together.[A]
[FarRight]You've killed Warlord Tyrone.[A]
[FarLeft]He was stubborn. He knew the chance was[NL]
there. My right-hand man, Connor... He[A][NL]
has ambitions for more than[NL]
peace. He wants to rule.[A]
[FarRight]And you desire something different!?[A]
[FarLeft]Yes. I believe the only one capable of[NL]
resolving the dispute between Arcanae and[A][NL]
Cesaria is Efil, the hero of the conflict[NL]
ten years ago. He should still reside in[A][NL]
the Temple of Kilthel in Draterus, but[NL]
we need an artifact to reach him.[A]
[FarRight]And you think this artifact will suffice?[A]
[Left]Yes, we do.[A]
[FarRight]Why should I trust you?[NL]
You murdered Tyrone.[A]
[Left]You have no reason to trust us. But we[NL]
did spare you. It would have been easy for[A][NL]
us to kill you and take it by force[A]
[FarLeft]As I said, Tyrone is stubborn. He[NL]
wouldn't have listened to us.[A]
[FarRight]Tyrone... Well, I suppose if I refuse,[NL]
you'll kill me. So I really have no choice.[A][NL]
Take the artifact and go to Draterus.[A]
[Left][Smile][FarLeft][Smile]You can tell the Basileus that our bandit[NL]
clan killed Tyrone. When he moves against[A][NL]
our headquarters, Connor will be the only[NL]
one there. It makes no difference[A][NL]
to us what their fate shall be.[A]
[FarRight]Very well. I wish you all luck...[A]
[Left]Thank you, sir.[A][X]