
## Merc7BanditBanditBeginningText
[FarLeft][LoadAdlez][Left][LoadPlayer][Right][LoadVicar][FarRight][LoadLeon]
I just received word that Cesaria and Arcanae[NL]
have mobilized. Unfortunately, they have[A][NL]
enacted a temporary truce until Bacrun is[NL]
under the Council of Guildsmen's control.[A]
[FarLeft]So we have to take them both[NL]
on at the same time... Alone?[A]
[FarRight]We still have the artifact. It will help[NL]
turn the tide. But we need to have a plan.[A][NL]
The main Haedrician force took heavy losses[NL]
while distracting the mercenaries,[A][NL]
but we should still have enough[NL]
to hold all sides of the city.[A]
[FarLeft]Most of my men are still around.[NL]
but they aren't much help[A][NL]
aganst an organized military.[A]
[FarRight]That's what I would've guessed. Under[NL]
most circumstances, I'd say we must[A][NL]
defend on the outer edge of Bacrun,[NL]
but we would spread our forces too[A][NL]
thinly. We need to fight them on the[NL]
streets, in a more individual context.[A]
[Left]That makes sense to me. Haedricians[NL]
aren't used to fighting in an[A][NL]
organized manner, anyway. It[NL]
certainly gives us an edge[A][NL]
over Cesaria and Arcanae.[A]
[FarRight]You are correct. Tight combat is a[NL]
Haedrician's specialty. We should leave[A][NL]
the main entrances to the city open, to[NL]
lure Cesaria and Arcanae's main forces[A][NL]
in. The other entrances can be defended[NL]
by the remainders of my forces. Any[A][NL]
splinter groups they try to sneak in[NL]
will be easily taken care of.[A]
[Right]Meanwhile, we take on their core[NL]
strike forces ourselves... It could[A][NL]
work. We also still have the[A][NL]
artifact. Have we tested the[NL]
limitations of its power?[A]
[FarLeft]We have not tested it, per se...[A]
[FarRight]Most artifacts of this type do have their[NL]
limitations. I would guess we only have a[A][NL]
few battalions of Vathrylians at our[NL]
disposal until the artifact loses its[A][NL]
energy and needs to recharge.[A]
[Right]So we have to rely on our own[NL]
skills and judgment. Against the[A][NL]
two biggest armies in Avenir.[A]
[FarRight]I trust you all. I believe we have a[NL]
chance. Now let's head out.[A][NL]
We have a hard fight ahead of us.[A][X]

## Merc7BanditBanditXavusText
[FarRight][LoadXavus]
These fools... They think they can[NL]
stand up to the might of Arcanae?[A][NL]
Men, burn them to the ground! We[NL]
must recapture this city for the[A][NL]
council! We've temporarily made[NL]
a truce with Cesaria, only[A][NL]
attack the Haedrician dogs![A][X]

## Merc7BanditBanditRexText
[FarLeft][LoadRex]
Soldiers of the Cesarian Army! Today, a[NL]
greater threat than Arcanae stands in[A][NL]
front of us. Move into the city and kill[NL]
the occupiers! Bacrun must be restored![A][X]

## Merc7BanditBanditXavusDeathText
[FarLeft][LoadXavus]
How were they able to do[NL]
this...? The power...[A][NL]
I never thought the[NL]
war would end...[....][CloseEyes] Like this...[A][X]

## Merc7BanditBanditRexDeathText
[FarLeft][LoadRex]
So this is how Cesaria falls...[NL]
To a horde of rabble...[A][NL]
The irony abounds...[A][X]

## Merc7BanditBanditGoodEndingText
[Right][LoadAdlez][FarRight][LoadPlayer][FarLeft][LoadVicar][Left][LoadLeon]
I can hardly believe it... Both[NL]
Xavus and Rex are... Dead...[A]
[Right]This is what we came for, is it not?[A]
[Left]But of course! Cesaria and Arcanae[NL]
are without their two greatest[A][NL]
leaders! We sure to garner support[NL]
from smaller rebellions now...[A]
[FarLeft]So does this mean...[A]
[Left]Yes. We've won. Cesaria and Arcanae have[NL]
lost a large portion of their fighting force[A][NL]
their two central leaders, as well as their[NL]
source of many resources here in Bacrun.[A]
[FarRight]It doesn't feel like we've really done[NL]
it... But we have. The war is virtually over.[A][ClearFace][LoadConnor]
We should take steps immediately[NL]
to establish our new governm-[A]
[Right]Connor?[A]
[FarRight]Yeah, boss?[A]
[Right]Shut up.[A]
[FarRight]Of course. Sorry, boss.[A]
[Right][Smile]Actually, you know what you can do?[A]
[FarRight]Yes?[A]
[Right]Execute the council of guildsmen.[NL]
There is no further use of them.[A]
[Left]I agree.[A]
[FarRight][Smile]Right away![A][ClearFace][Smile]
[FarLeft]So what does this mean for the rest of us?[A]
[Left]We'll start to establish a home[NL]
base here. I imagine many who[A][NL]
were against the war will rally[NL]
to our cause, and the remnants[A][NL]
of Arcanae and Cesaria won't stand[NL]
a chance. We've accomplished the[A][NL]
difficult part of our goal, however.[NL]
Vicar, if you and the boys wish[A][NL]
to go, you can feel free.[NL]
You too, [Tact].[A]
[FarRight][LoadPlayer]I'm sticking around.[A]
[FarLeft]I've seen all I need to see. If you[NL]
ever need us, you can call on us.[A][FarRight][ClearFace][LoadWalter]
Don't hesitate! We mercenaries are[NL]
always looking for work, as you know.[A][ClearFace][LoadBaret]
Just don't hire us for[NL]
stupid things, alright?[A]
[Right][Smile]Hahaha! Don't ever change, you three.[NL]
Thank you for all the help, Vicar.[A][FarRight][ClearFace][LoadArya]
It's about time for me to[NL]
hightail it out of here too. I[A][NL]
need to make my report to Xexim.[A]
[Left]What do you think he'll[NL]
do about all this?[A]
[FarRight]Probably nothing. So long as you[NL]
don't intend to come to Shizon.[A]
[Right]We have no interest in that. Thank you,[NL]
Arya. You've been nothing but helpful.[A]
[FarRight][Smile]
Just doing my job. Good luck with[NL]
the rest of your endeavors,[A][NL]
Adlez. Keep him in line, [Tact].[A][FarLeft][ClearFace][LoadPlayer][Smile]
Don't you worry about me.[A][FarRight][ClearFace]
[Left]Let's take a well-earned rest. We've[NL]
finished our job here. I can't[A][NL]
ask much more of any of you.[A]
[FarLeft]Thank you, Leon. For everything.[A]
[Left]No. Thank you, [Tact]. You too, Adlez. You[NL]
showed me how possible it is to stand up[A][NL]
to an injustice you don't agree with,[NL]
even when the forces you stand up to[A][NL]
are well beyond your capability. Good[NL]
work, both of you. Get some rest.[A][X]

## Merc7BanditBanditGoodEndingNarratorText
[MidRight][LoadPlayer][MidLeft][LoadNarrator]
Well, that was fun...[A]
[MidRight]What the hell!? Who are you!?[A]
[MidLeft]You don't remember, lost soul? How[NL]
pathetic. You think starting a bigger[A][NL]
war will prevent the current one? Fool.[A]
[MidRight]Lost soul? You make no sense.[A]
[MidLeft]Get away with what? Even though you're[NL]
a moron, you definitely entertained me.[A][NL]
But I can't just let this go on. See, by[NL]
letting you live your life, I've broken[A][NL]
the terms of my contract as Guardian[NL]
Spirit. So I'll have to kill you.[A]
[MidRight]Guardian Spirit...[.....] Wait![NL][LoadPlayer]
I remember you now![A]
[MidLeft]It's good that you'll end your life[NL]
with knowledge rather than ignorance.[A]
[MidRight]I'm not going out so easily...[A][X]

## Merc7BanditBanditGoodEndingPlayerDeathText
[FarRight][LoadPlayer]Dammit...[A][ClearFace]
[FarLeft][LoadNarrator]Ah, what a shame... Looks[NL]
like you are going[A][NL]
out so easily. See you[NL]
next time, [Tact]...[A][X]

## Merc7BanditBanditBadEndingText
[MidLeft][LoadLeon][Right][LoadPlayer][FarRight][LoadAdlez]
[Tact]! We can't do this![A]
[Right]We just have to keep pushing![A]
[MidLeft]Adlez is right, [Tact]. Xavus and[NL]
Rex's forces are too strong for us. We[A][NL]
should make our escape while we can.[A]
[Right]And go where?[A]
[FarRight]We can kill the Council of Guildsmen,[NL]
grab treasures from the vault, and escape[A][NL]
through the ruins beneath the city.[A]
[Right]Ruins beneath the city? You[NL]
didn't mention those earlier.[A]
[FarRight]I had Baret investigate potential[NL]
escape routes. I doubt anyone beyond the[A][NL]
Council of Guildsmen know of its existence,[NL]
so it'll be perfect for our needs.[A]
[Right]But Adlez... You wanted-[A]
[FarRight]I know what I wanted! We can escape now,[NL]
and that dream can live on, or we can[A][NL]
die here and have nothing. With the[NL]
council dead, Bacrun will be[A][NL]
incapacitated. The war will be a[NL]
mess regardless. We've done enough.[A]
[MidLeft]You all can make your choice, but[NL]
I'm ordering my men to retreat. With them[A][NL]
them gone, the entrances to the city will no[NL]
longer be defended. You won't last an hour.[A]
[Right]Leon...[A]
[MidLeft]Adlez already said it. We'd[NL]
rather let the dream live on[A][NL]
than die here. Goodbye, [Tact].[A][ClearFace][....]
[Left][LoadVicar]Baret, Walter! [FarLeft][LoadBaret][Left]We're going too.[A]
[FarLeft]Agreed.[A][ClearFace]
[LoadWalter]I'm sorry, [Tact]... This is it.[A][ClearFace][Left][ClearFace][FarRight]
What will you do, [Tact]?[A][CloseSpeech][Right][MoveLeft][ClearFace][LoadPlayer]
Let's grab the loot and go. You're right.[A]
[FarRight]Connor![A][FarLeft][LoadConnor]
Aye, boss?[A]
[FarRight]Get the clan moving. Kill the council,[NL]
grab any loot that isn't nailed down,[A][NL]
and go through the ruins beneath[NL]
the city. Baret is leading the way.[A][NL]
He scouted them out earlier.[A]
[FarLeft]Sounds good, boss. I won't question[NL]
your choice. I know this is hopeless.[A]
[FarRight]We flee now so that our hope[NL]
doesn't die. Now shut up and move![A]
[FarLeft]Yeah, boss![A][X]

## Merc7BanditBanditBadEndingRexXavusHereText
[FarRight][LoadArya][Right][LoadAdlez]
Damn. It's too late...[A][CloseSpeech][FarRight][MoveLeft]
[Events]
[Left]I'll hold them off. Go![A]
[FarRight][LoadPlayer][Right]Arya! I'm not paying you to die![A]
[Left]Shizonians do what we do in the[NL]
line of work. Sorry, Adlez. You[A][NL]
too, [Tact]... It's been a pleasure.[A]
[FarRight][LoadPlayer]Arya, no![A][X]

## Merc7BanditBanditBadEndingRexLineText
[FarLeft][LoadRex]Stand aside, assassin. I have no quarrel[NL]
with you. I simply want them.[A][ClearFace][X]

## Merc7BanditBanditBadEndingXavusLineText
[FarLeft][LoadXavus]Xexim's fools have no place here. If[NL]
you do not move, I will make you move.[A][ClearFace][X]

## Merc7BanditBanditBadEndingRexXavusLastLineText
[Left]Run![A][X]

## Merc7BanditBanditBadEndingTactAdlezText
[MidRight][LoadPlayer][MidLeft][LoadAdlez]
Dammit...[A]
[MidRight]We have to keep moving! Arya's[NL]
sacrifice will NOT be in vain![A][X]

## Merc7BanditBanditNarratorAdlezBattleText
[FarRight][LoadAdlez]Who the hell[NL]
are you?[A][ClearFace]
[FarLeft][LoadNarrator]I have no quarrel[NL]
with you. Begone.[A][X]

## Merc7BanditBanditBadEndingNarratorText
[MidRight][LoadNarrator][MidLeft][LoadPlayer]
Who the hell are you?[NL]
You're a monster...[A]
[MidRight]Monster? Not... quite. Can't say[NL]
I've heard that one before, lost soul.[A]
[MidLeft]What are you even saying?[A]
[MidRight]Do you not remember me? No, I suppose[NL]
you wouldn't... Nothing about like...[A][NL]
Giving you a new life? You creating[NL]
your own name, [Tact]?[A]
[MidLeft]Wait a minute... You can't be...[A]
[MidRight]Yes, yes, it's me, the Guardian[NL]
Spirit. Don't expect a tap dance[A][NL]
or something. That's not my style.[A]
[MidLeft]Why are you here!?[LoadPlayer] What[NL]
have you done to Adlez!?[A]
[MidRight]He's irrelevant at this point. You've[NL]
given me an awful lot of entertainment.[A][NL]
The fall of Bacrun would surely send both[NL]
Cesaria and Arcanae into an economic[A][NL]
downturn that could supposedly halt the[NL]
war but would probably just accelerate[A][NL]
the efforts. Unfortunately, we won't[NL]
get to see THAT result. You see, by[A][NL]
allowing you to affect events in this[NL]
way, I've broken my contract as[A][NL]
Guardian Spirit, but it's not too[NL]
late to kill you and roll time[A][NL]
back to before you started all this...[A]
[MidLeft]You what?[A]
[MidRight]I'm gonna kill you.[A]
[MidLeft]Wait, no! You can't![A]
[MidRight]Only reason I can't is if you can beat[NL]
me, which... Seems unlikely, but hey.[A][NL]
Give it your best shot, lost soul.[A][X]

## Merc7BanditBanditBadEndingPlayerDeathText
[FarRight][LoadPlayer]
Such power...[NL]
How can he...[A][ClearFace]
[FarLeft][LoadNarrator]I told you. I'm[NL]
the Guardian Spirit.[A][NL]
Goodbye, lost soul.[A][ClearFace]
[FarRight][LoadPlayer]Adlez...[NL]
I'm sorry...[A][ClearFace][X]
