
## Merc6BanditBanditBeginningText
[MidRight][LoadPlayer][MidLeft][LoadArya]
[Tact]! You're supposed to be[NL]
heading to the meeting![A]
[MidRight]I'm on my way, sorry! I'm[NL]
not used to navigating[A][NL]
buildings this big...[A]
[MidLeft]Here, I'll walk with you. Leon shared the[NL]
meeting room location with me yesterday.[A]
[MidRight]Thanks, Arya. It's my first time[NL]
in a castle quite this size. It's[A][NL]
definitely a bit of an adjustment.[A]
[MidLeft]The Temple on Shizon is filled with[NL]
underground chambers. It's said to be of a[A][NL]
civilization older than Vathryl, but our leader[NL]
doesn't really tell us a whole lot about it.[A]
[MidRight]Does that ever concern you?[A]
[MidLeft]Not really. Our leader, Xexim,[NL]
is honorable. We all trust him[A][NL]
with our lives and livelihoods.[A]
[MidRight]Why are you still here, anyway? I know[NL]
you wanted to see where this went, but I[A][NL]
think you've seen exactly where it's going.[A]
[MidLeft]Shizon may be a country of assassins[NL]
working for pay, but we actually heavily[A][NL]
advocate peace. Xexim has been looking to[NL]
end this conflict without interfering.[A]
[MidRight]Why can't he directly step in?[A]
[MidLeft]For one, Shizon lacks the manpower. We[NL]
may be skilled at one-on-one combat, but[A][NL]
we're not an organized fighting force, and[NL]
certainly don't have a huge quantity of[A][NL]
fighters. Additionally, Shizon has a set of[NL]
rules that we swear an oath to when we[A][NL]
join the order. They've existed for a long[NL]
time, and Xexim would rather cling to[A][NL]
those rules rather than forget the morals[NL]
we live by. One of those rules is we[A][NL]
can't directly intervene in the affairs[NL]
of nations. We can take pay to do jobs[A][NL]
for them, but nothing else.[A]
[MidRight]And you being here isn't[NL]
a direct intervention?[A]
[MidLeft]Adlez has been paying me. It's a[NL]
loophole in the system. Xexim wouldn't[A][NL]
use it himself, but I certainly can.[A]
[MidRight]I see... Well, I'm glad you're on our[NL]
side. You've proven very resourceful.[A]
[MidLeft]Glad to be of assistance. Here's the meeting[NL]
chamber. I think Leon has a plan.[A][X]

## Merc6BanditBanditPlanText
[FarRight][LoadLeon][Left][LoadVicar][FarLeft][LoadPlayer][Right][LoadAdlez]
Took you two long enough.[A]
[Left]It's fine, Adlez. Now that we're all here,[NL]
we should be able to begin? Leon?[A]
[FarRight]Yes. Just so we all understand, our goal[NL]
is to eradicate both Cesaria and Arcanae,[A][NL]
without taking a side in the war. Correct?[A]
[Right]Yes.[A]
[FarRight]Good. Now, I believe the linchpin[NL]
in this conflict is Bacrun...[A]
[FarLeft]Wouldn't it make sense to take the[NL]
two countries on one at a time?[NL]
Haedricians may be strong as[A][NL]
individuals, but there's far fewer[NL]
of us than there are soldiers in[A][NL]
either of the superpowers, not to[NL]
mention their superior organization.[A]
[FarRight]If we were to attack Cesaria,[NL]
Arcanae would think we were siding[A][NL]
with them. The opposite holds[NL]
true if we attack Arcanae. The[A][NL]
only way to remain neutral to[NL]
either side is to attack the[A][NL]
city they both rely heavily on.[A]
[FarLeft]I suppose that makes sense.[A]
[Left]So Bacrun, eh? The merchants' hub?[A]
[FarRight]Correct. It is an indispensable asset[NL]
to both countries. They may be at war[A][NL]
with each other, but the merchants[NL]
travelling to and from Bacrun keep both[A][NL]
their armies supplied with resources. If[NL]
we cut off that supply, we antagonize[A][NL]
both Arcanae and Cesaria, turning[NL]
their attention towards us[A][NL]
rather than each other.[A]
[FarLeft]The issue is that they are both after[NL]
us. We're strong, but I don't fancy[A][NL]
standing up to two superpowers with nothing[NL]
but a horde of bandits and Haedricians.[A]
[FarRight]You forget, we have the artifact. It[NL]
can summon Vathrylian guardians to aid us.[A]
[Left]Even so, we don't know if they can truly be[NL]
controlled. Would Cesaria and Arcanae[A][NL]
truly ally against us, or would it[NL]
become a three pronged conflict?[A]
[FarRight]Ideally, it will be a three way fight, but[NL]
we will have the advantage of the city.[A]
[Right]You're proposing we capture Bacrun,[NL]
and then allow them to come to us?[A]
[Left]How will we guarantee that?[A]
[FarRight]Even if they don't, Bacrun cycles all[NL]
resources that they either need from each[A][NL]
other or from us. They could choose to[NL]
ignore us, but sooner or later, they will[A][NL]
lose the support for the war effort.[A]
[FarLeft]So either they come to us and we fight[NL]
them off, or the war ends because they[A][NL]
run out of resources to maintain it...[A]
[Left]Hang on. Have we considered the possibility[NL]
that perhaps Cesaria or Arcanae would[A][NL]
attempt to counterattack Haedric and[NL]
lay ruin to our home?[A]
[Right]Neither Cesaria nor Arcanae have ever seemed[NL]
to have any interest in anything in[A][NL]
Haedric. Plus, with Bacrun obliterated by the[NL]
fighting there, they won't have sufficient[A][NL]
supplies to attack Haedric.[A]
[FarRight]Either way, we resolve their[NL]
conflict, without taking a side.[A]
[FarLeft]Why not negotiate with Bacrun?[NL]
Or even with Cesaria and Arcanae?[A]
[FarRight]Bacrun's Council of Guildsmen are all greedy[NL]
bastards, only caring about the coin.[A][NL]
Same with the mercenary group that defends[NL]
the city. As for Cesaria and Arcanae,[A][NL]
this war has gone on too long. Their base[NL]
ideals are just too vastly different.[A][NL]
Even if they resolve the war with a treaty,[NL]
there will be a level of hostility[A][NL]
politically, economically, even physically[NL]
along the border. The hero Efil[A][NL]
temporarily resolved it ten years ago,[NL]
but as we can see, it was only[A][NL]
temporary. If he couldn't do[NL]
it, I highly doubt we can.[A]
[FarLeft]So this is really our only option...[A]
[FarRight]That is correct. What do you all say?[A]
[Right]I have no idea that's better.[A]
[Left]I agree. It's our only real idea.[A][ClearFace][LoadArya]
I'm just along to see how this all goes.[NL]
So long as I get my pay, I'm happy.[A]
[FarRight]What about you, [Tact]?[A]
[FarLeft]I say we do it. As Adlez and Vicar said,[NL]
we have no better idea. We might as well[A][NL]
capture Bacrun and see where it takes us.[NL]
Even if we have to make a break for it[A][NL]
when the two superpowers come knocking,[NL]
we'll at least be a lot richer.[A]
[FarRight]I'm glad we are in agreement! Now,[NL]
I don't want to use the artifact[A][NL]
for this assault quite yet...[A]
[Right]So then what's the plan?[A]
[FarRight]I will lead Haedric's warriors on a full[NL]
frontal assault. Meanwhile, you all will[A][NL]
slip in through one of the many entrances[NL]
into Bacrun and move straight for the[A][NL]
Council of Guildsmen. You're likely to[NL]
encounter some resistance, but your[A][NL]
mission is simply to capture their building.[NL]
If you do that, we have all the bargaining[A][NL]
chips, and therefore, control of the city.[A]
[Left]So you will serve as a distraction?[A]
[FarRight]I'm the Basileus. They'd assume me to[NL]
lead the main strike force. If I lead the[A][NL]
distraction, it will serve to[NL]
legitimize the strategy.[A]
[FarLeft]Makes sense to me.[A]
[FarRight]Good! Let us ready ourselves and depart.[NL]
I've aranged for additional supplies[A][NL]
from my personal armory to be granted[NL]
to you for the assault. Use them well.[A][NL]
These winds of change are set to blow![A][X]

## Merc6BanditBanditAtBacrunText 
[Left][LoadVicar][Right][LoadPlayer][FarRight][LoadArya][FarLeft][LoadAdlez]
Ah, the mercantile city-state of Bacrun...[A]
[Left]How long has it been?[A]
[FarLeft]Too long.[A]
[Right]You've been here before?[A]
[FarLeft]Aye. Tyrone would send us to try and[NL]
negotiate for luxuries.[A]
[FarRight]I always thought Haedrician Warlords[NL]
lived a more spartan lifestyle...[A]
[Left]To an extent of course. Walter, Baret,[NL]
could you two scout ahead?[A][NL]
Make sure our route is clear.[A][FarRight][ClearFace][LoadBaret]
I'm on it.[A][ClearFace][LoadWalter]
I'll cover you, brother.[A][ClearFace][LoadConnor]
[FarLeft]Connor, keep an eye out for Leon's signal.[NL]
When you see the flash, we start moving.[A]
[FarRight]Shouldn't I help with the planning?[A]
[FarLeft]Shut up, Connor. Of course not.[A]
[FarRight]Right. Sorry, boss.[A][ClearFace][LoadArya]
You're really getting tired[NL]
of that one, aren't you?[A]
[FarLeft]He keeps assuming he's important. It drives[NL]
me nuts. He wanted to 'lead' our new[A][NL]
nation, but I trust Leon far more than[NL]
Connor. He has no morals.[A]
[Right]I can tell. Not that we're exactly[NL]
princes right now. I mean, we are[A][NL]
ransacking the central hub of Avenir's[NL]
whole economy. Anyway,  Adlez, what[A][NL]
do you happen to know about the mercenary[A][NL]
group that operates in Bacrun?[A]
[FarLeft]Their leader's name is Hawken. He's an[NL]
extremely skilled fighter, negotiator,[A][NL]
and leader. There's a reason the council[NL]
hires him, to put it mildly.[A]
[FarRight]What about his men?[A]
[FarLeft]Most of them originated in Haedric, just[NL]
by nature of our culture. They have the[A][NL]
fighting skills of Haedricians, but the[NL]
organization of a true military force.[A][NL]
Bacrun's independence is largely[NL]
attributed to them.[A]
[Right]So we need to keep our heads level.[A]
[FarLeft]Right. Even though we shouldn't face too[NL]
many thanks to Leon, they're all highly[A][NL]
trained. Even a small number could be[NL]
tough to deal with. But I think[A][NL]
we have a good group here.[A]
[Right]I agree.[A][FarRight][ClearFace][LoadBaret]
I'm back. Everything is largely clear[NL]
out there. Obviously some men stand[A][NL]
guard, but nothing too worrisome.[A]
[FarLeft]Not to mention Leon's distraction[NL]
hasn't quite started yet.[A]
[Right]I wouldn't be too quick to say[NL]
that. Leon just sent the signal.[A]
[FarRight]Walter should be returning[NL]
soon with an update, then.[A]
[FarLeft]So this is it, huh?[A]
[Left]Don't get too hasty. Capturing[NL]
Bacrun is the easy part.[A]
[FarLeft]You're right. Here comes Walter.[A][FarRight][ClearFace][LoadWalter]
Most of the force is[NL]
moving away. Let's go.[A]
[Left]We have to move quickly. The less time Leon[NL]
is under pressure, the better. We[A][NL]
can't hope to take on Cesaria[NL]
and Arcanae if Leon's force[A][NL]
is dead. Move out![A][X]

## Merc6BanditBanditHarkenText
[Left][LoadGuildsman][MidRight][LoadHawken]
Why has Leon suddenly decided on this course[NL]
of action...? It makes no sense...[A]
[Left]Hawken, what is going on?[A]
[MidRight]It seems the Basileus has led his army[NL]
here and demands control over the city.[A]
[Left]You can't let him! I don't[NL]
care how much he offers you![A]
[MidRight]I'm an honest man. I'm[NL]
not gonna be bribed.[A]
[Left]So what do you intend to do? They're[NL]
going to raze Bacrun to the ground![A]
[MidRight]We're Haedricians too.[NL]
They don't stand a chance.[A]
[FarLeft][LoadSoldier4]Hawken! There's a small group slipping in[NL]
an alternate entrance to the city![A][NL]
They're headed this way![A]
[MidRight]Leon, you clever bastard... Alright men! We[NL]
defend the Council's hall until Leon's[A][NL]
losses are too heavy! Roll over 'em, boys![A][X]

## Merc6BanditBanditTheyKnowText
[Left][LoadPlayer][FarLeft][LoadAdlez]
It seems they know we're coming...[A]
[Left]It's too late now. We have to commit.[NL]
Otherwise, we leave Leon for dead.[A]
[FarLeft]You're right. No turning back now.[A][FarRight][LoadConnor]
Should we grab anything not nailed[NL]
down? Create more chaos?[A]
[FarLeft]Might as well. These rats[NL]
have got plenty of money[A][NL]
to go around, after all.[A][X]

## Merc6BanditBanditHarkenBattleText
[FarLeft][LoadHawken]
You've made it this far,[NL]
but no further! I have[A][NL]
a job to do, and I've[NL]
never let down an employer![A][X]

## Merc6BanditBanditHarkenAdlezBattleText
[FarLeft][LoadHawken]You! I know you![A][ClearFace]
[FarRight][LoadAdlez]Can't say I'm surprised.[A][ClearFace]
[FarLeft][LoadHawken]You're Adlez! That bandit leader![NL]
You've been wanted for years.[A][NL]
Every mercenary in Haedric has[NL]
wanted to claim the bounty on[A][NL]
your head. Seems[Smile] like it's[NL]
my lucky day.[A][ClearFace]
[FarRight][LoadAdlez]I wouldn't count your[NL]
blessings just yet...[A][ClearFace]
[FarLeft][LoadHawken]Wait a minute... Basileus Leon ia[NL]
here... Why are you working with[A][NL]
him? What's the meaning of this?[A][ClearFace]
[FarRight][LoadAdlez]You want answers? You'll[NL]
have to defeat us first.[A][ClearFace]
[FarLeft][LoadHawken]Dammit.[A][X]

## Merc6BanditBanditHarkenDeathText
[FarLeft][LoadHawken]
Dammit...[....] Guess I...[.....][NL]
underestimated them...[A][X]

## Merc6BanditBanditEndingText
[FarRight][LoadAdlez][Right][LoadPlayer][Left][LoadGuildsman]
Hawken... Damn you-![A]
[Right]Stand down! The city is[NL]
under our control![A]
[Left]Your control!? Bacrun is[NL]
under nobody's control![A]
[FarRight]Connor, take[FarLeft][LoadConnor][FarRight] him to the council chamber[NL]
with the rest of the guildsmen and lock[A][NL]
them up. We're not here to kill them, but we[NL]
don't want them in our way when Cesaria[A][NL]
and Arcanae come knocking...[A]
[FarLeft]I'm on it.[A][Left][ClearFace][FarLeft][ClearFace][LoadBaret][Left][LoadVicar][FarLeft]
Adlez, with the building secured and Hawken[NL]
dead, most of the mercenaries are[A][NL]
fleeing. Shall we go after them?[A]
[FarRight]Don't bother, I need you all here[NL]
right now. Vicar, what's the[A][NL]
status on Leon and his men?[A]
[Left]I just sent Walter to go to the main[NL]
western gate. He should be back soon.[A]
[FarRight]Good. We need to regroup quickly,[NL]
I'm sure word will reach Cesaria[A][NL]
and Arcanae before long.[A][CloseSpeech][FarLeft][ClearFace][Left][ClearFace][Right][MoveMidLeft][ClearFace][LoadPlayer]
What's our strategy to defend from[NL]
them when they arrive?[A][CloseSpeech]
[FarRight][MoveMidRight]We can use the city to our advantage. The[NL]
alleyways will allow us to fight them[A][NL]
in small numbers more easily...[A]
[MidLeft]What about the artifact? We can[NL]
use that to our advantage, can't we?[A]
[MidRight]Of course. I certainly intend to be making[NL]
use of the Vathrylian guardians as we[NL]
fight. They are strong, yet expendable.[A]
[MidLeft]We just have to be careful.[A][CloseSpeech][MoveLeft][FarLeft][LoadWalter]
Leon's men have broken through. Most of[NL]
the mercenaries fled when they heard of[A][NL]
Hawken's death. Leon himself is[NL]
en route here now.[A]
[MidRight]Good. We'll need to[NL]
strategize to pull this next[A][NL]
stage of the operation off...[A][X]