
## Merc3MilitiaKillBeginningText
[MidLeft][LoadArc][Right][LoadPlayer]Good morning Arc![A][NL]
[MidLeft]G'morning. Any sign of Luke yet?[A]
[Right]No.[A][NL]
[FarRight][LoadLuke]Sorry. Here I am.[.....] Couldn't sleep well.[A][NL]
[Right]No matter. So we're[NL]
heading to the capital?[A][NL]
[MidLeft]Yeah. The other caravan didn't arrive,[NL]
but we're going to head out anyway.[A][NL]
Hopefully we'll meet them on the road.[A][NL]
[Right]Sounds like a plan.[....] Let's get going.[NL]
I've prepared a small convoy of useful[NL]
useful weapons just in case.[A]
[FarRight]Good. Let's head out.[A][X]

## Merc3MilitiaKillRuinsText
[FarLeft][LoadLuke]This place is still standing after all of[NL]
these centuries. It's a shame it's[A][NL]
fallen into disrepair.[A][CloseSpeech][FarRight][LoadArc][FarLeft][MoveLeft]
[FarLeft][LoadPlayer][FarRight][LoadArc]At least those damn Arcanaeans haven't[NL]
gotten their hands on it. I-[A][NL][Events]
[.......]...[.......] What is this?[A][NL]
[Left]It's the other caravan...[.......][NL]
They're...[.......] all dead...[....][A][NL]
[FarLeft]Who did this?![A][X]

## Merc3MilitiaKillWestonHereText
[FarLeft][LoadLuke][Left][LoadArc][MidRight][LoadWeston]That would be us.[....] We're out to avenge[NL]
Gerwick. We thought this[A][NL]
might bring you out.[A][CloseSpeech][MoveFarRight][Left][MoveRight]
[Right]Damn you![A][CloseSpeech][FarLeft][MoveLeft]
Arc! Calm down![A]
[FarLeft][LoadPlayer]They're not calm, we[NL]
have no reason to be calm.[A]
[FarRight]Hahaha! I always love a good fight.[NL]
We'll take what you have and use it to[A][NL]
destroy Danaan![....] What would they do without[NL]
their fearless militia leader, Arc?[A]
[Right]Danaan is my home. Gerwick screwed it[NL]
up once. I'm not gonna[A][NL]
let anybody do any more![A][NL]
[FarRight]Well then, let's see how much[NL]
you can truly do. Come on boys![A][ClearFace]
[Left]We're in a bad position here![A][CloseSpeech]
[Right][MoveMidRight]Lemme at 'em![A][NL]
[Left]You have to be calmer, Arc.[NL]
Nothing productive will get done.[A][CloseSpeech]
[MidRight][ClearFace][.][LoadArc]You're just clinging to your ways.[A]
[FarLeft]Arc, we don't have time for this. We'll[NL]
handle this like we handled Gerwick.[A]
[Left]Right.[A]
[MidRight]Fine then.[.....] Let's fight![A][X]

## Merc3MilitiaKillWestonAryaText
[MidLeft][LoadArya][MidRight][LoadWeston]You there![A][NL]
[MidLeft]The name is Arya.[A][NL]
[MidRight]You're just a Shizonian.[....] Your name[NL]
isn't important. See that man there, Arc?[A][NL]
[MidLeft]Yes...[A][NL]
[MidRight]He's your main target.[A][NL]
[MidLeft]This was not the job I signed up for.[NL]
This is banditry,[.] not assassination.[A][NL]
[MidRight]You'll get paid more than[NL]
promised. Now just go![A][CloseSpeech]
[MidLeft][TMM][.......]... [.......][TMM]Very well.[A][X]

## Merc3MilitiaKillAryaArcText
[MidLeft][LoadArc][MidRight][LoadArya]Your name is Arc, correct?[A][NL]
[MidLeft]What's it to you?[A][NL]
[MidRight]You're my target. Get ready.[A][NL]
[MidLeft]Wait! Me specifically?[A][NL]
[MidRight]That is what I was told to do.[A][NL]
[MidLeft]What kind of bandit are you?[NL]
Firstly, you're a girl.[A][NL]
Secondly, you have a target?[A][NL]
[MidRight]I am an assassin of Shizon. I will[NL]
kill whomever my employer orders me to.[A][NL]
[MidLeft]This seems to be below the typical[NL]
jobs you Shizonians take on.[A][NL]
[MidRight][TMM][.......]... [.......][TMM]I may lack confidence in my orders,[NL]
but my contract is my contract.[A][NL]
[MidLeft]If your contract stated something[NL]
different than this, is it still valid?[A][NL]
[MidRight]What?[A][NL]
[MidLeft]I'm just a simple militiaman.[NL]
I'm no scholar, and certainly not an[A][NL]
assassin, but I figure that if Gerwick's[NL]
ole pal over there misled you, you'd[A][NL]
have the right to leave him, no? Plus,[NL]
Gerwick, your employer is dead.[A][NL]
[MidRight]Gerwick is dead?[A][NL]
[MidLeft]By our own hands.[NL]
Wouldn't that terminate your contract?[A][NL]
[MidRight]Then I'm no longer[NL]
bound to these bandits.[A][NL]
[MidLeft]How about this? How about I[NL]
contract you for our side?[A][NL]
[MidRight][TMM][.......]... [.......][TMM]I'll take any opportunity to get[NL][Smile]
back at these misleading thugs.[A][NL][ClearFace]
[MidLeft]Wow,[.] can't believe that worked.[A][X]

## Merc3MilitiaKillAryaLukeText
[MidLeft][LoadLuke][MidRight][LoadArya]Get out of my way.[NL]
You aren't my target.[A][NL]
[MidLeft]Stop! Why do you fight?[A][NL]
[MidRight]It is my duty, as my contract decrees.[NL]
We all have our reasons.[A][NL]
Why would you even care?[A][NL]
[MidLeft]I'm having doubt about...[.......][NL]
well...[.......] everything. What do the[NL]
Higher Beings truly want with us[NL]
Lower Beings? Why would they care?[A][NL]
[MidRight]Oh you're a monk are you?[NL]
Get out of my way. If you survive[A][NL]
this battle, maybe there will be a[NL]
chance for you to discover.[A][NL]
But if you die now...[.....][A][NL]
[MidLeft]I don't think you're doing[NL]
something you want to either.[A][NL]
[MidRight]What?[A][NL]
[MidLeft]You've hesitated thus far. Why?[A][NL]
[MidRight][TMM][.......]... [.......][TMM]I don't like this.[A][NL]
[MidLeft]Why?[A][NL]
[MidRight][TMM][.......]... [......][TMM]My contract said[NL]
nothing about banditry.[A][NL]
[MidLeft]Then come with us.[NL]
We can find our way together.[A][NL]
[MidRight]Perhaps. What is your name?[A][NL]
[MidLeft]Luke.[A][NL]
[MidRight]Very well then, Luke.[....] I am Arya.[Smile][NL]
Maybe I can help you uncover your truths.[A][X]

## Merc3MilitiaKillAryaPlayerText
[MidLeft][LoadPlayer][MidRight][LoadArya]You. Who are you?[A][NL]
[MidLeft]I could ask you the same.[A][NL]
[MidRight]My name is Arya.[NL]
I am an assassin from Shizon.[A][NL]
[MidLeft]Really? Banditry is more a[NL]
freelancer's job, not an assassin.[A][NL]
[MidRight]You've yet to answer my question.[A][NL]
[MidLeft]I'm [Tact], a freelancer[NL]
hired to guard this caravan.[A][NL]
And I'm doing just that.[A][NL]
[MidRight]You seem to have honor...[......][NL]
Any sane person would know[A][NL]
this is a losing battle.[A][NL]
[MidLeft]I believe this is a[NL]
conversation, not a fight.[A][NL]
[MidRight]I'm...[......] conflicted...[......][NL]
I'd rather not fight you.[A][NL]
[MidLeft]Banditry seems below you.[A][NL]
[MidRight]Yes...[......] You're right.[NL]
Perhaps I'll join you for now.[A][NL]
[MidLeft]Well...[......] We'd be honored to have you.[A][X]

## Merc3MilitiaKillWestonBattleText
[FarLeft][LoadWeston]Grr...[......] So this is[NL]
what Gerwick faced...[....][A][NL]
I'll avenge him,[.][NL]
here and now![A][X]

## Merc3MilitiaKillWestonAryaBattleText
[FarLeft][LoadWeston]You! What have you done?[A][ClearFace]
[FarRight][LoadArya]You broke the contract.[A][ClearFace]
[FarLeft][LoadWeston]I hired you to kill![A][ClearFace]
[FarRight][LoadArya]You hired me to kill one man.[NL]
Not massacre a caravan.[A][NL]
We of Shizon don't[NL]
do bad business.[A][NL]
I hope you understand.[A][NL][ClearFace]
[FarLeft][LoadWeston]Dammit![A][X]

## Merc3MilitiaKillAryaDeathText
[FarLeft][LoadArya]This is below me to die[NL]
here. I'm pulling out.[A][X]

## Merc3MilitiaKillEndingText
[MidRight][LoadLuke][Left][LoadPlayer][FarLeft][LoadArc]Some people...[A][NL]
[MidRight]Calm down Arc, please.[A][NL][MoveRight][FarRight][LoadArya]
[Left]It doesn't matter now. Let's go.[A][NL]
[FarRight]Wait.[A][NL]
[Right][MoveLeft][ClearFace][LoadLuke][Right]Oh. It's you. You need something?[A][NL]
[FarRight]I want you all to come back[NL]
with me. To Shizon.[A][NL]
[FarLeft]Haha, to that island in the[NL]
middle of nowhere? Why?[A][NL]
[FarRight]You are honorable people. Good[NL]
fighters. You would be welcome there.[A]
[Left]You've all turned your back on[NL]
the Higher Beings, though.[A][NL]
[FarRight]Please, Luke.[....] You'll understand if you[NL]
just come. Arc, with these bandits dead,[A][NL]
there's nothing left of Gerwick's clan.[A][NL]
[Right]Hold up. My job is guarding the caravan.[NL]
I can't leave that unfinished.[A][NL]
[FarLeft]There's a checkpoint just a few miles down[NL]
the road. We can stop there and[A][NL]
finish this discussion then.[A][NL]
[Right]I'm interested. I want to see the world.[NL]
[Smile]I've always wanted to go, and this may[A][NL]
be my only chance.[A]
[ClearFace][LoadPlayer]
Are you two in?[A][NL]
[FarLeft]Danaan is my home. You can hardly expect[NL]
me to just abandon them like this.[A]
[Left]I also.[A]
[FarRight]As Arc said, there's a checkpoint[NL]
down the road. Let's finish[A][NL]
this discussion there.[A]
[Right]Sounds good to me.[A][X]

## Merc3MilitiaKillEndingNoAryaText
[FarLeft][LoadLuke][Left][LoadPlayer][Right][LoadArc]Some people...[A]
[Left]Calm down Arc, please.[A]
[Right]It doesn't matter now. Let's go.[A][FarRight][LoadArya]
[Left]Arc![.] Behind you![A][MoveMidLeft][FarRight][LoadArya]
[Right]Eh?[A][CloseSpeech][MoveLeft][ClearFace][LoadArc][FarRight][MoveRight][Left][ClearFace][FarRight][LoadArc]
[Right]Ah! Stop! Let go![A]
[FarRight]Who are you? Who sent you?[A]
[Right]I'm from Shizon.[....] I was sent to kill you.[A]
[FarLeft]You were one of them,[.] weren't you?[NL]
I never thought as Shizonians as bandits.[A]
[Right]I never did either. I've dishonored[NL]
my people by following this contract.[A][NL]
[FarRight]I wish you luck in the afterlife![A]
[MidLeft][MoveLeft]Stop! She clearly wasn't loyal to the[NL]
bandits themselves. We should let her go.[A]
[Right]I...[.......] I want to make this up to you and[NL]
prove to you that we are not so barbaric.[A][NL]
I want you all to come back[NL]
with me. To Shizon.[A]
[FarRight]You are honorable people. Good[NL]
fighters. You would be welcome there.[A]
[Right]You are honorable people. Good fighters.[NL]
You would be welcome there.[A]
[FarLeft]You've all turned your back on[NL]
the Higher Beings, though.[A]
[Right]Please, Luke. You'll understand if you[NL]
just come. Arc, with these bandits dead,[A][NL]
there's nothing left of Gerwick's clan.[A]
[Left]Hold up. My job is guarding the caravan.[NL]
I can't leave that unfinished.[A]
[FarRight]There's a checkpoint just a few miles[NL]
down the road. We can stop there[A][NL]
and finish this discussion then.[A]
[Left]I'm interested. I want to see the world.[NL]
I've always wanted to go, and this[A][NL]
may be my only chance. Are you two in?[A]
[FarLeft]Danaan is my home. You can hardly expect[NL]
me to just abandon them like this.[A]
[Left]I also.[A]
[FarRight]As Arc said, there's a checkpoint[NL]
down the road. Let's finish[A][NL]
this discussion there.[A]
[Right]Sounds good to me.[A][X]

## Merc3MilitiaKillAryaAIText
[MidLeft][LoadArya][CloseEyes][TMM] [.......]... [.......][TMM][A]
[FarFarRight]You![A]
[MidLeft][OpenEyes]Ah![A]
[FarRight][LoadBandit1]The boss says you're up.[NL]
Get moving![A][ClearFace]
[MidLeft][CloseEyes][TMM] [.......]... [.......][TMM][OpenEyes][A][X]

## Merc3MilitiaKillWestonDeathText
[FarLeft][LoadWeston]Holy Hell. You guys are tough.[NL]
Who would have thought you[A][NL]
could take on my army?[A][X]

## Merc3MilitiaKillCheckpointText
[MidLeft][LoadArya][FarRight][LoadLuke][Right][LoadArc]
So why is it you want all[NL]
of us to go to Shizon?[A]
[MidLeft]My role here has reflected badly[NL]
on my homeland. We aren't bandits.[A][NL]
We aren't terrorists. We're assassins with[NL]
honor. I never wanted to attack that[A][NL]
caravan. I feel as though you all[NL]
may not believe that fact.[A]
[FarRight]I believe you. I just don't see a reason[NL]
why I should want to go somewhere like[A][NL]
that. I've heard the rumors of the[NL]
Cult of Shizon. You've turned your[A][NL]
backs on the Higher Beings.[A]
[MidLeft]That's not true, though, Luke.[A]
[FarRight]What do you mean?[A]
[MidLeft]The leader of our order, Xexim,[NL]
has spoken with Higher Beings[A][NL]
before. He knows the truth.[A]
[FarRight]Spoken with them? And... the truth...?[NL]
What truth? Why should I believe you?[A]
[MidLeft]You don't have a lot of reason to trust me,[NL]
but you claim to be fully dedicated to[A][NL]
the Higher Beings. I'm telling that you'll[NL]
understand more about them and about[A][NL]
yourself if you go to Shizon.[A]
[FarRight]More about them...[....] And about me...[....][NL]
What if you're wrong?[A]
[MidLeft]It's not a one-way trip. If you decide once[NL]
you're there that it's not worth your[A][NL]
time, getting you back home will be even[NL]
easier than getting you to Shizon will be.[A]
[FarRight][TMM]...[.....][TMM] Very well. I'll go. Arc?[A]
[Right]I'm not convinced. I couldn't give two[NL]
shits about whether the Higher Beings are[A][NL]
real or not. All I care about is keeping[NL]
Danaan safe from this war. A war you[A][NL]
Shizonians claim to have no part of[NL]
but only prolong with your work![A]
[MidLeft][TMM]...[....][TMM] I will admit... You raise a very fair point.[NL]
It is true that we seem hypocritical by[A][NL]
claiming to be neutral, while we make our[NL]
services available to either side. But[A][NL]
I'm telling you, Arc, you'll understand[NL]
everything more if you come with us.[A][NL]
Danaan will be safe in your absence. This[NL]
is your opportunity to see the world.[A]
[Right]What makes you think I want to[NL]
see the world? I'm a woodsman.[A]
[MidLeft]Is it not typical of Haedrician men to[NL]
desire to journey Avenir, fighting the[A][NL]
strongest foes to prove their strength?[A]
[Right]So what if it is?[A]
[MidLeft]You're turning down the opportunity to go to[NL]
a land where the entire culture is based[A][NL]
being a strong assassin- a deadly one-on-one[NL]
fighter...[Smile][....] perhaps being even[A][NL]
better than a Haedrician warrior.[A]
[Right]When you put it like that, it is mighty[NL]
tempting... No Shizonian is stronger than[A][NL]
a Haedrician warlord. I'll easily prove that[NL]
one to you, but there's still Danaan.[A]
[FarRight]Arc, we killed Gerwick. There shouldn't be[NL]
anything more to worry about there.[A][NL]
Besides, we weren't the only members of the[NL]
militia. This is a tremendous opportunity.[A]
[Right]What about [Tact]?[A]
[MidLeft][Tact] already made a choice.[NL]
It's time to make yours, Arc.[A]
[Right]I suppose...[....][Events] I'll go.[A]
[MidLeft]You will? That's fantastic![A]
[FarRight]I'm glad you came around, Arc.[NL]
So, what next, Arya?[A]
[MidLeft][Tact] has already gone on ahead to try[NL]
to contact the person who can get us to[A][NL]
Shizon. We'd best be on our way. Port[NL]
Selsing in Arcanae is our destination.[A][X]
