
## Military5PassHaedricBeginningText
[FarLeft][LoadElanil][Right][LoadSekar][FarRight][LoadPlayer][Left][LoadJasper]
I can't believe Haedric has fallen...[A]
[FarRight]I would've thought that their border[NL]
force would have been able to hold[A][NL]
off, even in the Basileus' absence...[A]
[Right]The Warlords don't always work together well[NL]
without his leadership. Without him there,[A][NL]
I imagine our fighting force became less and[NL]
less unified rather quickly. Between that[A][NL]
and Uzkalis' renewed assault, it seems[NL]
fair that our border guard failed.[A]
[FarLeft]You seem rather calm about[NL]
this whole thing, Sekar.[A]
[Right]Retaking Haedric will be easy. The[NL]
concentration of Inge within the country[A][NL]
won't suit the Arcanian forces, not to[NL]
mention the local resistance that[A][NL]
militias will be able to contribute[NL]
once we start our assault.[A]
[FarRight]What is the plan, anyway?[A]
[Left]I believe they are currently discussing[NL]
that now. The treaty has been finished to[A][NL]
create an alliance, but they still need[NL]
to figure out a good strategy[A][NL]
to minimize potential losses.[A]
[FarLeft]They also can't afford to devote all[NL]
their resources to Haedric. If Haedric has[A][NL]
fallen, Altia needs to strengthen it's[NL]
border, and the defense against Arcanae's[A][NL]
assaults towards Cesaria needs to be[NL]
reinforced as well. Losing Haedric[A][NL]
is bad on multiple fronts.[A]
[Right]Looks like your Sergeants are coming now,[NL]
Jasper. Maybe they'll have an update for us.[A][ClearFace][FarRight][ClearFace][LoadChristina][Right][LoadForrest]
[Left]Sergeant Forrest! Sergeant[NL]
Christina! What's the word?[A]
[Right]We're going to be joining[NL]
the assault on Haedric.[A]
[FarRight]It's going to be an attack on a few fronts.[NL]
Captain Sylvaine is planning to head up[A][NL]
north to assist the Anguis in defending[NL]
Altia's border in case Arcanae makes a push[A][NL]
up there. Elanil, you've been assigned[NL]
to continue working with us, as[A][NL]
well as Cougar and Finoc.[A]
[FarLeft]Very well. I'll let them know.[A][ClearFace]
[Right]Basileus Leon and Warlord Tyrone are[NL]
planning on leading the remnants of[A][NL]
Haedric's warriors into Haedric as a main[NL]
assault on the capital. We're going to be[A][NL]
one of multiple small strike forces trying[NL]
to liberate a larger town. Lady Muriel[A][NL]
will also lead a force into Haedric[NL]
with the main task of defending[A][NL]
the Ingefonts from Uzkalis.[A]
[Left]So our main task is liberating civilians,[NL]
rather than taking on Arcanae?[A]
[FarRight]That would be correct.[A][FarLeft][LoadPlayer]
I see no issue with that. It makes[NL]
sense that Basileus Leon and Warlord[A][NL]
Tyrone would want to actually[NL]
retake the capital themselves.[A][ClearFace][LoadSekar]
Will I be travelling with you all or[NL]
should I rejoin the Basileus and Tyrone?[A]
[Right]The Basileus requested that you lead us[NL]
through Haedric. None of us know the way[A][NL]
through Haedric, so it would be[NL]
most efficient for you to come with us.[A]
[FarLeft]I have no qualms with that. Do you know[NL]
what town we're moving towards first?[A]
[Right]The Basileus wanted us to check a town[NL]
called Deidar. Do you know where that is?[A]
[FarLeft]I do. It's one of the larger towns within[NL]
Haedric. I can easily escort you there.[A][NL]
When do you want us to move out?[A]
[FarRight]The Basileus and Tyrone plan on moving[NL]
out as soon as they're able. I'd like us to[NL]
do the same. Corporal Jasper, if you[A][NL]
round up your men, we'll be good.[A]
[Left][Tact] is already here, I'll[NL]
just have to hunt down Derek.[A][FarLeft][ClearFace][LoadElanil]
I'll go and grab Cougar and Finoc and[NL]
bring them up to speed. We should[A][NL]
be ready to leave within the hour.[A]
[FarRight]Perfect. Reconvene at the city gate[NL]
in about an hour then. Dismissed.[A][X]

## Military5PassHaedricDerekTactJasperText
[FarLeft][LoadPlayer][Left][LoadJasper][MidRight][LoadDerek]
So, we're going to Haedric next?[A]
[Left]Seems that way.[A]
[FarLeft]Never would have thought we'd have[NL]
fought in almost every country in Avenir[A][NL]
by the end of our campaign out here.[A]
[Left]Especially since this started[NL]
off as a simple diplomacy mission...[A]
[MidRight][MoveMidRight]Right!? Here I was hoping for[NL]
some peace and quiet...[A]
[Left]Derek! How do you think Sekar feels about[NL]
his country being taken right now?[A]
[MidRight]I was kidding, Jasper! Calm down![A]
[FarLeft]Ha! I at least finally feel like we're[NL]
doing something important in the war...[A]
[Left][Tact], they just ratified a military[NL]
alliance between Altia, Haedric, and[A][NL]
Cesaria. If what we're doing now[NL]
is important, that's important.[A]
[FarLeft]I suppose...[A]
[MidRight]It looks like the rest are[NL]
getting ready to head out.[A]
[Left]Right. Let's go retake Haedric.[A][X]

## Military5PassHaedricGateText
[Left][LoadChristina]
Are we all here?[A][Right][LoadClara]
Lady Muriel instructed me to stick[NL]
with you, in case there's a need for[A][NL]
someone with knowledge about magic.[A]
[Left]We're happy to have you, Clara.[A][FarLeft][LoadFinoc]
All three of us are accounted for.[A]
[Left]Perfect. Sergeant Forrest and Sekar[NL]
went on ahead already. Corporal Jasper?[A][FarRight][LoadJasper]
We're all here.[A]
[Left]Perfect! Most of you know this already,[NL]
but our objective is the Haedrician town[A][NL]
of Deidar. It's a larger city, somewhat[NL]
close to the capital. The Basileus said[A][NL]
it was crucial to retake that town to gain[NL]
the assistance of the militia there.[A]
[FarLeft]Understood. I take it we're going to head[NL]
out and catch up to Forrest and Sekar?[A]
[Left]Yes. If you and Cougar can fly up and[NL]
get a rough idea of where they[A][NL]
currently are, that would be perfect.[A]
[FarLeft]You can count on us.[A]
[Left]Jasper, you and [Tact] will take point with[NL]
me. Elanil and Derek can cover our rear.[A]
[FarRight]Yes, ma'am.[A]
[Left]Let's get going![A][X]

## Military5PassHaedricTravelText
[MidLeft][LoadChristina][MidRight][LoadPlayer]
Sergeant, is Basileus Leon planning[NL]
to retake the capital himself?[A]
[MidLeft]Yes. He and Warlord Tyrone have rallied[NL]
the remnants of the other Warlords and[A][NL]
their forces to head straight for the[NL]
capital, picking up militia groups as[A][NL]
they go. We're to take the militia at[NL]
Deidar straight to the capital once we[A][NL]
defeat the Arcanian occupation there.[A]
[MidRight]But aren't Haedricians generally at[NL]
a disadvantage against Arcanians?[A]
[MidLeft]How do you mean?[A]
[MidRight]I mean, magic has the advantage of range[NL]
and there's no way to easily resist it.[A]
[MidLeft]That's true. Haedricians have managed[NL]
to adapt. The concentration of Inge in[A][NL]
Haedric helps give them the energy they[NL]
need to deal with the magic. Looks like[A][NL]
we've caught up to Forrest and[NL]
Sekar. Sekar probably has a[A][NL]
better answer to your question.[A][CloseSpeech][MoveLeft][FarLeft][LoadSekar]
What's that?[A]
[MidRight]How do you Haedricians deal with[NL]
the Arcanians? I'd think you'd[A][NL]
have a disadvantage against[NL]
their skills with magic.[A]
[FarLeft]Ah, yeah I can see why you'd think that.[NL]
We're pretty hardy folk, though. A few[A][NL]
spells won't be enough to bring us down[NL]
quickly, so we can fare pretty well[A][NL]
in battle against them so long[NL]
as we stay on our toes.[A]
[MidRight]I suppose that makes sense... We[NL]
Cesarians normally just accept some[A][NL]
losses and deal with the issue.[A]
[FarLeft]We Haedricians value each other's lives[NL]
and don't have the strength in numbers.[A]
[Left]That's enough on that topic. It depends[NL]
on the Captain in charge. Most of[A][NL]
the Captains are not so blind to the[NL]
lives of their soldiers as you may think.[A]
[FarLeft]I'm just going off of what [Tact][NL]
said, I know nothing about Cesarian[A][NL]
battle tactics as a country. It[NL]
sounds vastly different from[A][NL]
how we Haedricians fight though.[A]
[Left]That's a given. How close[NL]
are we to Deidar?[A]
[FarLeft]Not too far now. We might want to discuss[NL]
battle strategy. Before moving in.[A]
[Left]Makes sense. Forrest? What do you think?[A][FarLeft][ClearFace][LoadForrest]
Cougar, Finoc! Scout ahead. Try to get[NL]
an estimate on numbers and defenses. We[A][NL]
need to know what we're up against.[A][MidRight][ClearFace][FarRight][LoadCougar][Right][LoadFinoc]
Understood![A]
[FarRight]We're on it![A]
[FarLeft]Everyone else, get your gear[NL]
together. We'll need to be ready.[A][X]

## Military5PassHaedricUzkalisText
[MidRight][LoadUzkalis][MidLeft][LoadDunlas]
Lord Uzkalis, the treaty has been signed.[NL]
Spies report multiple enemy forces moving[A][NL]
through Haedric to counter our occupation.[A]
[MidRight]So, they're eager to retake Haedric?[NL]
Interesting... Understandable, of course,[A][NL]
but we didn't come here to capture[NL]
Haedric's government or enslave their[A][NL]
people. Dunlas, have you found[NL]
the locations of the Ingefonts?[A]
[MidLeft]No, my lord.[A]
[MidRight]Unfortunate... Make sure to keep our[NL]
defenses strong. We will find the[A][NL]
Ingefonts, Leon must have a[NL]
record of them somewhere here.[A]
[MidLeft]Understood.[A]
[MidRight]You're dismissed.[MidLeft][ClearFace][MidRight] Xavus...[NL]
Hold out, my old friend.[A][....][FarLeft][LoadSoldier1]
Lord Uzkalis! The Basileus[NL]
is on our doorstep![A]
[MidRight]What!? Already? Damn...[A]
[FarLeft]What should we do?[A]
[MidRight]All of them are expendable, but...[NL]
Keep Basileus Leon alive. He will[A][NL]
be of good use for us. We[NL]
cannot fall to these fools.[A]
[FarLeft]Understood![A][X]

## Military5PassHaedricHereText
[FarLeft][LoadPlayer][Left][LoadForrest][Right][LoadSekar][FarRight][LoadCougar]
There's an Arcanian Captain and a few[NL]
squadrons in the city. It doesn't look as[A][NL]
though they've really established a militant[NL]
occupation though. They're mostly[A][NL]
patrolling in the streets. Civilians just[NL]
avoid them. No sign of if the militia is[A][NL]
there or not, I'd guess they're fine.[A]
[Right]Most civilians would be on the militia. I[NL]
doubt they'd join us in battle, however.[A][NL]
They'd have to recognize me, and they[NL]
wouldn't join up with Cesarians.[A]
[FarLeft]You're a direct servant to[NL]
the Basileus though, aren't you?[A]
[Right]I'm just a warrior that fights alongside him[NL]
fairly often. The only other Haedricians[A][NL]
they might know outside of their community[NL]
would be Warlords, and they likely[A][NL]
wouldn't recognize them at sight.[A]
[FarLeft]I suppose I wouldn't recognize[NL]
Captain Zalius if I met him...[A]
[Right]Exactly.[A]
[Left]So our best bet is head in while[NL]
the Arcanians are unprepared?[A]
[FarRight]Yeah. They'll definitely put up[NL]
a bit of a fight, but now's[A][NL]
as good a time to attack as any.[A]
[Left]Let's move in then.[A][X]

## Military5PassHaedricStartBattleText
[MidRight][LoadShanley]
We're under attack? Damn, I didn't expect[NL]
Haedric to mobilize against us so quickly.[A][NL]
We have to hold this city. For Lord Uzkalis![A][X]

## Military5PassHaedricShanleyBattleText
[FarLeft][LoadShanley]
Cesarians and Altians?[NL]
What is this? Was the[A][NL]
treaty not interrupted?[A][X]

## Military5PassHaedricShanleyDeathText
[FarLeft][LoadShanley]
Lord Uzkalis... Did[NL]
you... lie to us...?[A][X]

## Military5PassHaedricEndingText
[Right][LoadForrest]
I think that's all of the soldiers eliminated.[A][ClearFace][MidRight][LoadElanil][MidLeft][LoadChristina]
I'll check on the civilians.[A]
[MidRight]Cougar, Finoc, and I can help with that.[A]
[MidLeft]Thank you, Elanil.[A][ClearFace][MidRight][ClearFace][Right][CloseEyes][LoadShanley][FarRight][LoadForrest]
The Arcanian Captain is still alive.[A][MidLeft][LoadSekar]
I'll interrogate him. Maybe he can[NL]
shed some light on Uzkalis' plans.[A][FarRight][ClearFace]
[Right][MoveMidRight]You know as much as I do...[A]
[MidLeft]What do you mean?[A]
[MidRight]Lord Uzkalis...[OpenEyes] Instructed us to hold[NL]
this city to prevent the militia from[A][NL]
resisting. He said the treaty would be[NL]
unsuccessful from Dunlas' attack. I[A][NL]
didn't expect to see this alliance...[A]
[MidLeft]What was his reason[NL]
for attacking Haedric?[A]
[MidRight]What do you mean? This is war, isn't[NL]
it? You conquer other countries...[A][CloseSpeech][MidLeft][MoveLeft][FarLeft][LoadClara]
But Haedric is useless to Arcanae.[NL]
Did you just blindly follow Uzkalis?[A]
[MidRight]He believed the Ingefonts would be[NL]
useful. He and Lord Xavus are much[A][NL]
wiser than the rest of us, so[NL]
we felt no need to question it...[A]
[FarLeft]So they are after the Ingefonts...[A]
[MidRight]You won't be able to stand up to[NL]
Lord Uzkalis. We were just a[A][NL]
small force... His men are more[NL]
skilled than I am, and he himself...[A]
[Left]I think that's enough out of you.[A][CloseSpeech][MoveRight][....][MidRight][ClearFace][FarLeft][MoveFarLeft]
Sekar![A][Right][ClearFace][LoadSekar]
What were you going to do,[NL]
leave him alive? Set him free?[A]
[FarLeft]Senseless murder isn't necessary![A][FarRight][LoadForrest]
What's happening over here?[A]
[FarLeft]Sekar just-[A]
[Right]We got what we wanted out of him.[A]
[FarRight]Hm. Sekar, we're a squadron, under my[NL]
command and Christina's. Don't do[A][NL]
something rash like that again.[NL]
Understood? I know you Haedricians[A][NL]
are very independent, but we[NL]
need you to work with us on this.[A]
[Right][TMM]...[....][TMM] Very well. I apologize.[A]
[FarRight]Clara, is there a way for[NL]
you to reach Lady Muriel?[A]
[FarLeft]She's the Lady of the Wind.[A]
[FarRight][TMM]...[.......][TMM] Yeah, and?[A]
[FarLeft]It's easy to reach her.[NL]
I'll get on that right away.[A][ClearFace]
[FarRight]Perfect. Jasper![A][MidLeft][LoadJasper]
Yes, Sergeant?[A]
[FarRight]Head to the inn and see if the innkeeper[NL]
is able to host us for the night. If we[A][NL]
have to sleep in the stable, that's fine.[A]
[MidLeft]Understood.[A][ClearFace][FarLeft][LoadDerek][Left][LoadPlayer]
What do you need Derek and me to do?[A]
[FarRight]You two are on watch. We don't know[NL]
enough about Uzkalis' deployments[A][NL]
to trust that there's no[NL]
other enemy squadrons nearby.[A]
[FarLeft]You can count on [Tact] and me.[A]
[FarRight]Perfect. Let's take a rest until[NL]
we hear back from Lady Muriel[A][NL]
regarding our next move.[A][X]

## Military5PassHaedricHouse1Text
[FarRight][LoadCurrent][FarLeft][LoadVillagerWoman]
The Arcanians haven't done a lot to[NL]
assert their dominance over us, but[A][NL]
they did confiscate all of the weapons[NL]
any of us kept in our homes. We're[A][NL]
defenseless to fight back. I did[NL]
manage to hide my husband's tomahawk[A][NL]
away before they came... He tried to[NL]
resist and was killed. Take it.[A][NL]
Split an Arcanian's skull with[NL]
it. He would have liked it.[A][X]

## Military5PassHaedricHouse2Text
[FarRight][LoadCurrent][FarLeft][LoadVillagerMan5]
We have this antique lance left by some[NL]
mercenary who came through here[A][NL]
awhile ago... None of us could ever[NL]
quite figure out what was so special[A][NL]
about it. The Arcanians didn't confiscate[NL]
it for some reason. Here, take it. It's[A][NL]
not doing any good gathering dust here.[A][X]

## Military5PassHaedricHouse3Text
[FarRight][LoadCurrent][FarLeft][LoadVillagerGirl3]
People often wonder why Haedricians grow[NL]
to be such strong warriors without[A][NL]
really being able to train at a young[NL]
age. Well, we have these scrolls[A][NL]
that can teach you a lot about how[NL]
to fight and wield weapons without[A][NL]
ever having to pick one up.[NL]
Here, take it and try it out.[A][NL]
You might learn a little.[A][X]

